// Top individual and corporate donors for 2026 Nebraska statewide races
// (Governor, Secretary of State, Attorney General, State Treasurer, Auditor
// of Public Accounts).
//
// Hand-maintained, not scraped -- sourced directly from the Nebraska
// Accountability and Disclosure Commission's (NADC) bulk contribution/loan
// data exports (nadc-e.nebraska.gov/PublicSite/DataDownload.aspx), covering
// the 2023-2026 filing years as extracted 8/14/2026 (Governor race), 8/21/2026
// (Secretary of State and Attorney General races), and 8/22/2026 (Treasurer
// and Auditor races). Figures are cycle-to-date totals for each candidate's
// registered committee, aggregated by donor name across all four years and
// ranked by total dollars given. Excludes the state's own "$250-or-less, not
// itemized" small-dollar aggregate line and PAC/party-committee money
// (tracked separately, not shown here). Lists are top 10 by dollar amount,
// or fewer where a candidate simply doesn't have 10 distinct donors on file
// in that category (noted per-candidate below where that applies).
//
// individualDonorCount / individualAverage are computed across ALL itemized
// individual contributions (not just the top 10 shown), excluding NADC's
// lump-sum "$250-or-less" bucket -- there's no way to recover a donor count
// from that bucket since NADC reports it as a single unitemized total.
//
// geography.{individual,corporate} splits ALL itemized contributions in
// that category (again, not just the top 10) into Nebraska vs. out-of-state
// by the donor's reported mailing address state. A candidate with zero
// itemized corporate donors (e.g. Foley) has `corporate: null` rather than
// a zero/zero split, since there's nothing to chart.
//
// COMMITTEES MATCHED:
// - Governor: "Jim Pillen for Governor," "Lynne Walz for Nebraska." Rick
//   Beard (Legal Marijuana Now) has no registered committee -- hasn't
//   crossed the $5,000 reporting threshold. Brett Lindstrom (independent)
//   filed a committee ("Friends of Lindstrom") but didn't gather enough
//   valid petition signatures to make the general-election ballot, so he's
//   intentionally excluded.
// - Secretary of State: "Petersen for Nebraska" (Scott Petersen) and
//   "Slattery for Nebraska" (Sarah Slattery). Petersen also has an older,
//   much smaller committee ("Friends of Scott Petersen," ~$2,000 raised in
//   2025 only) that appears to predate this campaign -- excluded here in
//   favor of his current, active committee.
// - Attorney General: "Friends of Mike Hilgers" (Mike Hilgers) and
//   "Brasher for NE AG" (Jocelyn Brasher).
// - State Treasurer: "Spellerberg for Nebraska" (Joey Spellerberg). He also
//   has an unrelated committee, "Joey Spellerberg for Mayor," from an
//   earlier Fremont mayoral run ($758K+ raised there) -- excluded here since
//   it isn't this race. Dan Ebers has no registered committee on file, so no
//   donor data exists for him.
// - Auditor of Public Accounts: Mike Foley (unopposed) -- his contributions
//   are combined from two committees, "Foley for the People- Auditor (2022)"
//   and "Foley for the People- Auditor (2026)." The "(2022)" committee is
//   his real ongoing committee (active every year 2023-2026, ~$71,750
//   total); "(2026)" is a newer, much smaller filing (~$1,500). Both appear
//   to fund the same current officeholder/candidate, so they're combined.
//
// REVISIT: these are cycle-to-date snapshots, not final. Update after later
// NADC filing deadlines as the general election nears.

const governorDonors = {
  "Jim Pillen": {
    committeeName: "Jim Pillen for Governor",
    totalRaised: 12927971,
    asOf: "2023\u20132026 NADC filings (cycle to date)",
    individualDonorCount: 694,
    individualAverage: 8403,
    geography: {
      individual: { nebraska: 5528168, outOfState: 359997 },
      corporate: { nebraska: 4573005, outOfState: 1410736 },
    },
    corporate: [
      { name: "POET, LLC", location: "Sioux Falls, SD", amount: 300000 },
      { name: "Union Pacific Railroad Company", location: "Omaha, NE", amount: 285000 },
      { name: "Alliance Omaha Soccer LLC (dba Union Omaha)", location: "Papillion, NE", amount: 150000 },
      { name: "KAAPA Ethanol Holdings, LLC", location: "Kearney, NE", amount: 145000 },
      { name: "American Family Life Assurance Co. of Columbus (AFLAC)", location: "Columbus, GA", amount: 140000 },
      { name: "Chief Industries, Inc.", location: "Grand Island, NE", amount: 130000 },
      { name: "Siouxland Ethanol LLC", location: "Jackson, NE", amount: 125000 },
      { name: "Blackshirt Feeders LP", location: "Benkelman, NE", amount: 125000 },
      { name: "Wholestone Farm II, LLC", location: "Fremont, NE", amount: 100000 },
      { name: "Foote Cattle Company LLC", location: "Bucyrus, KS", amount: 100000 },
    ],
    individual: [
      { name: "Shawn Peed", location: "Lincoln, NE", amount: 285000 },
      { name: "Thomas (Tom) Peed", location: "Lincoln, NE", amount: 285000 },
      { name: "Guy Ellsworth", location: "Pierce, NE", amount: 250000 },
      { name: "Rachel Werner", location: "Valley, NE", amount: 250000 },
      { name: "C.G. Holthus", location: "York, NE", amount: 131000 },
      { name: "Joseph Hausmann", location: "Roca, NE", amount: 117500 },
      { name: "Scott Cassels", location: "Omaha, NE", amount: 100500 },
      { name: "Matthew Sheehy", location: "Englewood, CO", amount: 100000 },
      { name: "Cara Whitney", location: "Walton, NE", amount: 100000 },
      { name: "Judd Norman", location: "Lincoln, NE", amount: 80000 },
    ],
  },
  "Lynne Walz": {
    committeeName: "Lynne Walz for Nebraska",
    totalRaised: 1476123,
    asOf: "2023\u20132026 NADC filings (cycle to date)",
    individualDonorCount: 504,
    individualAverage: 1795,
    geography: {
      individual: { nebraska: 871147, outOfState: 33724 },
      corporate: { nebraska: 73077, outOfState: 0 },
    },
    corporate: [
      { name: "Mountain to Climb LLC", location: "Omaha, NE", amount: 45000 },
      { name: "Nebraska Groundswell", location: "Lincoln, NE", amount: 13551 },
      { name: "Nebraska & Southwest Iowa Building & Construction Trades Council", location: "Omaha, NE", amount: 10000 },
      { name: "Groundswell", location: "Lincoln, NE", amount: 1776 },
      { name: "Nebraska State AFL-CIO", location: "Lincoln, NE", amount: 1500 },
      { name: "Warhorse Gaming LLC", location: "Winnebago, NE", amount: 1000 },
      { name: "American Communications Group, Inc.", location: "Lincoln, NE", amount: 250 },
    ],
    individual: [
      { name: "Dianne Lozier", location: "Omaha, NE", amount: 265000 },
      { name: "Barbara Weitz", location: "Omaha, NE", amount: 150000 },
      { name: "Annette Smith", location: "Omaha, NE", amount: 100000 },
      { name: "Beth Eliason", location: "Yutan, NE", amount: 35000 },
      { name: "Katie Weitz", location: "Omaha, NE", amount: 25000 },
      { name: "John Kotouc", location: "Omaha, NE", amount: 5250 },
      { name: "Steven Lathrop", location: "Omaha, NE", amount: 5000 },
      { name: "Coleen Stice", location: "Omaha, NE", amount: 5000 },
      { name: "Allen Fredrickson", location: "Omaha, NE", amount: 5000 },
      { name: "Matthew Johnson", location: "Omaha, NE", amount: 5000 },
    ],
  },
};

const secretaryOfStateDonors = {
  "Scott Petersen": {
    committeeName: "Petersen for Nebraska",
    totalRaised: 140304,
    asOf: "2023\u20132026 NADC filings (cycle to date)",
    individualDonorCount: 46,
    individualAverage: 1469,
    geography: {
      individual: { nebraska: 65625, outOfState: 1000 },
      corporate: { nebraska: 2250, outOfState: 0 },
    },
    corporate: [
      { name: "Penner Patient Care Inc", location: "Aurora, NE", amount: 1000 },
      { name: "Printco Graphics", location: "Omaha, NE", amount: 1000 },
      { name: "Pinnacle Bank", location: "Lincoln, NE", amount: 250 },
    ],
    individual: [
      { name: "Mike Moran", location: "Omaha, NE", amount: 20000 },
      { name: "Sam Sampson", location: "Lincoln, NE", amount: 16750 },
      { name: "Perry Petersen", location: "Omaha, NE", amount: 5000 },
      { name: "Mike Faust", location: "Omaha, NE", amount: 2000 },
      { name: "Berniece Grewcock", location: "Omaha, NE", amount: 2000 },
      { name: "Leo Eledge", location: "Omaha, NE", amount: 1000 },
      { name: "Richard Smith", location: "Omaha, NE", amount: 1000 },
      { name: "Matt Murphy", location: "Omaha, NE", amount: 1000 },
      { name: "Ann Francis", location: "Omaha, NE", amount: 1000 },
      { name: "Carole Julian", location: "Omaha, NE", amount: 1000 },
    ],
  },
  "Sarah Slattery": {
    committeeName: "Slattery for Nebraska",
    totalRaised: 38567,
    asOf: "2023\u20132026 NADC filings (cycle to date)",
    individualDonorCount: 127,
    individualAverage: 187,
    geography: {
      individual: { nebraska: 22392, outOfState: 1380 },
      corporate: { nebraska: 7852, outOfState: 0 },
    },
    corporate: [
      { name: "Planned Parenthood Advocates of Nebraska", location: "Lincoln, NE", amount: 3352 },
      { name: "Warhorse Gaming", location: "Winnebago, NE", amount: 2500 },
    ],
    individual: [
      { name: "Elizabeth Constance", location: "Omaha, NE", amount: 5000 },
      { name: "Rick Vest", location: "Lincoln, NE", amount: 2500 },
      { name: "Katie Weitz", location: "Omaha, NE", amount: 2500 },
      { name: "Mary Fischer", location: "Lincoln, NE", amount: 1500 },
      { name: "Jane Kleeb", location: "Hastings, NE", amount: 1000 },
      { name: "Megan Hull", location: "Oakland, CA", amount: 1000 },
      { name: "Ann Trullinger", location: "Gothenburg, NE", amount: 632 },
      { name: "Teresa Lorensen", location: "Avoca, NE", amount: 500 },
      { name: "Kathleen Thuman", location: "Lincoln, NE", amount: 500 },
      { name: "Sharlette Schwenninger", location: "Elwood, NE", amount: 450 },
    ],
  },
};

const attorneyGeneralDonors = {
  "Mike Hilgers": {
    committeeName: "Friends of Mike Hilgers",
    totalRaised: 1966935,
    asOf: "2023\u20132026 NADC filings (cycle to date)",
    individualDonorCount: 124,
    individualAverage: 3560,
    geography: {
      individual: { nebraska: 189350, outOfState: 249499 },
      corporate: { nebraska: 261080, outOfState: 707500 },
    },
    corporate: [
      { name: "Reynolds American Inc. / RAI Services", location: "Winston-Salem, NC", amount: 95000 },
      { name: "The Hurst Group LLC", location: "Jackson, MS", amount: 60000 },
      { name: "KAAPA Ethanol Holdings, LLC", location: "Kearney, NE", amount: 47500 },
      { name: "Stonebrook Exterior", location: "Lincoln, NE", amount: 40000 },
      { name: "Altria Client Services, Inc.", location: "Richmond, VA", amount: 36000 },
      { name: "Anheuser-Busch Companies", location: "St. Louis, MO", amount: 32500 },
      { name: "SidePrize LLC and Affiliates (d/b/a PrizePicks)", location: "Atlanta, GA", amount: 30000 },
      { name: "FanDuel Inc", location: "New York, NY", amount: 27500 },
      { name: "Hawkins Construction Company", location: "Omaha, NE", amount: 25000 },
      { name: "Nomi Health, Inc", location: "Orem, UT", amount: 25000 },
    ],
    individual: [
      { name: "Miriam Adelson", location: "Las Vegas, NV", amount: 75000 },
      { name: "Jeremy Lieberman", location: "New York, NY", amount: 22138 },
      { name: "Stacie Stern", location: "Brooklyn, NY", amount: 20000 },
      { name: "Tonn Ostergard", location: "Lincoln, NE", amount: 20000 },
      { name: "Thomas (Tom) Peed", location: "Lincoln, NE", amount: 20000 },
      { name: "Shawn Peed", location: "Lincoln, NE", amount: 20000 },
      { name: "Michael Cassling", location: "Omaha, NE", amount: 15000 },
      { name: "Adam Piper", location: "Raleigh, NC", amount: 10000 },
      { name: "William Austin", location: "Brownsville, TX", amount: 10000 },
      { name: "Tani Dru Austin", location: "Brownsville, TX", amount: 10000 },
    ],
  },
  "Jocelyn Brasher": {
    committeeName: "Brasher for NE AG",
    totalRaised: 177182,
    asOf: "2023\u20132026 NADC filings (cycle to date)",
    individualDonorCount: 48,
    individualAverage: 2407,
    geography: {
      individual: { nebraska: 111163, outOfState: 8000 },
      corporate: { nebraska: 15317, outOfState: 0 },
    },
    corporate: [
      { name: "Groundswell", location: "Lincoln, NE", amount: 13317 },
      { name: "Nebraska Groundswell", location: "Lincoln, NE", amount: 1000 },
    ],
    individual: [
      { name: "Barbara Weitz", location: "Omaha, NE", amount: 50000 },
      { name: "Dianne Lozier", location: "Omaha, NE", amount: 10000 },
      { name: "Dolores Brady", location: "Omaha, NE", amount: 5000 },
      { name: "Harley Schrager", location: "Omaha, NE", amount: 5000 },
      { name: "Beth Eliason", location: "Yutan, NE", amount: 5000 },
      { name: "Ronald Streck", location: "Vero Beach, FL", amount: 5000 },
      { name: "Elizabeth Constance", location: "Omaha, NE", amount: 5000 },
      { name: "Katie Weitz", location: "Omaha, NE", amount: 3628 },
      { name: "Daniel Wintz", location: "Papillion, NE", amount: 1500 },
      { name: "Edith Peebles", location: "Omaha, NE", amount: 1500 },
    ],
  },
};

const treasurerDonors = {
  "Joey Spellerberg": {
    committeeName: "Spellerberg for Nebraska",
    totalRaised: 379136,
    asOf: "2023\u20132026 NADC filings (cycle to date)",
    individualDonorCount: 81,
    individualAverage: 1722,
    geography: {
      individual: { nebraska: 131890, outOfState: 8100 },
      corporate: { nebraska: 57213, outOfState: 4000 },
    },
    corporate: [
      { name: "All Metals Market, Inc", location: "Fremont, NE", amount: 10000 },
      { name: "Wholestone Farm II, LLC", location: "Fremont, NE", amount: 10000 },
      { name: "Fremont Beef Company", location: "Fremont, NE", amount: 10000 },
      { name: "Hawkins Construction Company", location: "Omaha, NE", amount: 5000 },
      { name: "S2 Rolloffs, LLC", location: "Fremont, NE", amount: 5000 },
      { name: "Nebraska Bank", location: "Dodge, NE", amount: 2500 },
      { name: "Mueller Robak, LLC", location: "Lincoln, NE", amount: 2500 },
      { name: "Charter Communications", location: "St Louis, MO", amount: 2500 },
      { name: "Adams and Sullivan Attorneys", location: "Papillion, NE", amount: 2500 },
      { name: "Great Plains Communications, Inc.", location: "Blair, NE", amount: 1500 },
    ],
    individual: [
      { name: "Sid Dillon", location: "Fremont, NE", amount: 10000 },
      { name: "Thomas Weitzenkamp", location: "Hooper, NE", amount: 10000 },
      { name: "Jeff Wilmes", location: "Valley, NE", amount: 10000 },
      { name: "Robert Murray", location: "Fremont, NE", amount: 10000 },
      { name: "J Peter (Pete) Ricketts", location: "Omaha, NE", amount: 10000 },
      { name: "Steve Roy", location: "Alex City, AL", amount: 5000 },
      { name: "Marlin Brabec", location: "Ames, NE", amount: 5000 },
      { name: "Blake Dillon", location: "Fremont, NE", amount: 5000 },
      { name: "Samuel Heineman", location: "Fremont, NE", amount: 5000 },
      { name: "Lorelee Byrd", location: "Arlington, NE", amount: 5000 },
    ],
  },
};

const auditorDonors = {
  "Mike Foley": {
    committeeName: "Foley for the People- Auditor",
    totalRaised: 73257,
    asOf: "2023\u20132026 NADC filings (cycle to date)",
    individualDonorCount: 35,
    individualAverage: 1344,
    geography: {
      individual: { nebraska: 52550, outOfState: 2500 },
      corporate: null,
    },
    corporate: [],
    individual: [
      { name: "Deb Placek", location: "Lincoln, NE", amount: 6500 },
      { name: "Richard Clements", location: "Elmwood, NE", amount: 5000 },
      { name: "Donald Dillon", location: "Lincoln, NE", amount: 3000 },
      { name: "Joseph Kerrigan", location: "Lincoln, NE", amount: 2500 },
      { name: "Richard Noel", location: "Lincoln, NE", amount: 2500 },
      { name: "Peter Demarco", location: "Springfield, NE", amount: 2000 },
      { name: "Matt Tasler", location: "Lincoln, NE", amount: 2000 },
      { name: "Susan Meckel", location: "Lincoln, NE", amount: 2000 },
      { name: "Mary Volkmer", location: "Lincoln, NE", amount: 2000 },
      { name: "Mike Lawlor", location: "Omaha, NE", amount: 1500 },
    ],
  },
};

// Top individual and corporate donors for the 25 Nebraska Legislature races
// on the 2026 ballot. Same sourcing/methodology as the statewide races
// above (NADC bulk contribution/loan extracts, 2023-2026, extracted
// 8/22/2026), excluding the "$250-or-less" aggregate bucket and PAC/party
// money. Matched by cross-referencing each candidate's name against NADC's
// "Candidate Name" field, then confirming the correct committee where a
// candidate had multiple registered committees (e.g., an older committee
// from a prior race) or where a last name matched multiple unrelated
// people.
//
// Excluded as unrelated even though a name/last-name matched: any
// committee tied to a different office (city council, school board,
// county sheriff, OPPD board, etc.) or to a different candidate who
// happens to share a last name.
//
// Five candidates have no registered NADC committee as of this extract --
// Colby L. Woodson (Dist. 28), Dan Winter (Dist. 24), Tobias Howard
// (Dist. 26), Shaylee S. Scranton (Dist. 42), and Jessica M. Landers
// (Dist. 48) -- so no donor data exists to show for them.

const legislatureDonors = {
  "Brad von Gillern": {
    committeeName: "Von Gillern For Nebraska",
    totalRaised: 421668,
    asOf: "2023\u20132026 NADC filings (cycle to date)",
    individualDonorCount: 69,
    individualAverage: 1906,
    geography: {
      individual: { nebraska: 125798, outOfState: 7750 },
      corporate: { nebraska: 116567, outOfState: 51320 },
    },
    corporate: [
      { name: "H & H Automotive", location: "Omaha, NE", amount: 25000 },
      { name: "Peter Kiewit Sons' INC.", location: "Omaha, NE", amount: 10000 },
      { name: "Cox Communications", location: "Wichita, KS", amount: 7600 },
      { name: "Hawkins Construction Company", location: "Omaha, NE", amount: 7500 },
      { name: "BNSF Railway Company", location: "Fort Worth, TX", amount: 6000 },
      { name: "Kiewit Corporation", location: "Omaha, NE", amount: 5000 },
      { name: "Woodsonia Real Estate, INC.", location: "Elkhorn, NE", amount: 5000 },
      { name: "Alliance Omaha Soccer LLC DBA Union Omaha", location: "Papillion, NE", amount: 5000 },
      { name: "Tenaska, INC.", location: "Omaha, NE", amount: 3700 },
      { name: "Von Gillern Properties LLC", location: "Omaha, NE", amount: 3500 },
    ],
    individual: [
      { name: "Tom Schleich", location: "Lincoln, NE", amount: 20000 },
      { name: "Michael Cassling", location: "Omaha, NE", amount: 12500 },
      { name: "John McCoy", location: "Kearney, NE", amount: 10410 },
      { name: "Tom Schleich", location: "Bennet, NE", amount: 10000 },
      { name: "Peter Gamboian", location: "Omaha, NE", amount: 5250 },
      { name: "Dick Bell", location: "Omaha, NE", amount: 5000 },
      { name: "Fred Hawkins", location: "Omaha, NE", amount: 5000 },
      { name: "George Little", location: "Scottsdale, AZ", amount: 5000 },
      { name: "Richard Bell", location: "Omaha, NE", amount: 5000 },
      { name: "Fred Hunzeker", location: "Omaha, NE", amount: 5000 },
    ],
  },
  "John Fredrickson": {
    committeeName: "Friends For John Fredrickson",
    totalRaised: 403834,
    asOf: "2023\u20132026 NADC filings (cycle to date)",
    individualDonorCount: 57,
    individualAverage: 1650,
    geography: {
      individual: { nebraska: 86011, outOfState: 14564 },
      corporate: { nebraska: 72655, outOfState: 48754 },
    },
    corporate: [
      { name: "Planned Parenthood Advocates Of Nebraska", location: "Lincoln, NE", amount: 17485 },
      { name: "Cox Communications", location: "Wichita, KS", amount: 6142 },
      { name: "Hawkins Construction Company", location: "Omaha, NE", amount: 6000 },
      { name: "Interior Systems Union Local 1306", location: "La Vista, NE", amount: 5000 },
      { name: "Murphy-Neilan Trust", location: "San Francisco, CA", amount: 5000 },
      { name: "Nextera Energy Resources, LLC", location: "Juno Beach, FL", amount: 5000 },
      { name: "Great Plains Communications, INC.", location: "Blair, NE", amount: 4919 },
      { name: "Charter Communications", location: "St Louis, MO", amount: 4000 },
      { name: "Kissel Kohout Es Associates LLC", location: "Lincoln, NE", amount: 3652 },
      { name: "Consolidated Companies, INC.", location: "Lincoln, NE", amount: 3351 },
    ],
    individual: [
      { name: "Allen Fredrickson", location: "Omaha, NE", amount: 12500 },
      { name: "Allen Frederickson", location: "Omaha, NE", amount: 12500 },
      { name: "Katie Weitz", location: "Omaha, NE", amount: 7000 },
      { name: "Michael Cassling", location: "Omaha, NE", amount: 6000 },
      { name: "Teresa Welch", location: "Corvallis, OR", amount: 5889 },
      { name: "Dianne Lozier", location: "Omaha, NE", amount: 5000 },
      { name: "Annette Smith", location: "Omaha, NE", amount: 4000 },
      { name: "Marc Dubois", location: "Omaha, NE", amount: 2500 },
      { name: "Matt Rokowsky", location: "Jackson, NJ", amount: 2000 },
      { name: "Jolene Burdine", location: "Omaha, NE", amount: 2000 },
    ],
  },
  "George Dungan": {
    committeeName: "George For Nebraska",
    totalRaised: 334337,
    asOf: "2023\u20132026 NADC filings (cycle to date)",
    individualDonorCount: 42,
    individualAverage: 849,
    geography: {
      individual: { nebraska: 28076, outOfState: 7580 },
      corporate: { nebraska: 76046, outOfState: 49825 },
    },
    corporate: [
      { name: "Bold Alliance", location: "Hastings, NE", amount: 20000 },
      { name: "Reynolds American INC. / Rai Services", location: "Winston Salem, NC", amount: 8500 },
      { name: "Nextera Energy Resources, LLC", location: "Juno Beach, FL", amount: 5000 },
      { name: "Altria Client Services, INC. (Va)", location: "Richmond, VA", amount: 5000 },
      { name: "Horsemen'S Exposition & Racing INC. DBA Horsemens Park", location: "Omaha, NE", amount: 5000 },
      { name: "Planned Parenthood Advocates Of Nebraska", location: "Lincoln, NE", amount: 4427 },
      { name: "Kissel Kohout Es Associates LLC", location: "Lincoln, NE", amount: 3166 },
      { name: "Invenergy, LLC", location: "Chicago, IL", amount: 3000 },
      { name: "Panama Energy Center, LLC", location: "Juno Beach, FL", amount: 2500 },
      { name: "Cannabis Factory", location: "Omaha, NE", amount: 2500 },
    ],
    individual: [
      { name: "Dianne Lozier", location: "Omaha, NE", amount: 5000 },
      { name: "Teresa Welch", location: "Corvallis, OR", amount: 3000 },
      { name: "Gary Green", location: "Sag Harbor, NY", amount: 2500 },
      { name: "Douglas Fenn", location: "Lincoln, NE", amount: 2100 },
      { name: "Susan Tast", location: "Lincoln, NE", amount: 2000 },
      { name: "George Dungan", location: "Denton, TX", amount: 2000 },
      { name: "Jennifer Houlden", location: "Lincoln, NE", amount: 1500 },
      { name: "Todd Lancaster", location: "Lincoln, NE", amount: 1500 },
      { name: "Albert Davis", location: "Lincoln, NE", amount: 1000 },
      { name: "Alicia Henderson", location: "Lincoln, NE", amount: 1000 },
    ],
  },
  "Mike Jacobson": {
    committeeName: "Mike Jacobson For Legislature",
    totalRaised: 282697,
    asOf: "2023\u20132026 NADC filings (cycle to date)",
    individualDonorCount: 26,
    individualAverage: 990,
    geography: {
      individual: { nebraska: 24307, outOfState: 1920 },
      corporate: { nebraska: 42065, outOfState: 55970 },
    },
    corporate: [
      { name: "Romph & Pou Agency, INC.", location: "Shreveport, LA", amount: 5000 },
      { name: "Pacific Life Insurance Company", location: "Newport Beach, VA", amount: 5000 },
      { name: "Olson Farms, INC.", location: "North Platte, NE", amount: 5000 },
      { name: "Molina Healthcare INC", location: "Long Beach, CA", amount: 4500 },
      { name: "Charter Communications", location: "St Louis, MO", amount: 3500 },
      { name: "Centene Management Company LLC", location: "St. Louis, MO", amount: 3500 },
      { name: "Cox Communications", location: "Wichita, KS", amount: 3261 },
      { name: "Copic Insurance Company", location: "Denver, CO", amount: 3000 },
      { name: "Kaapa Ethanol Holdings, LLC", location: "Kearney, NE", amount: 2500 },
      { name: "Fat Dog", location: "North Platte, NE", amount: 2500 },
    ],
    individual: [
      { name: "Jerry Adams", location: "Broken Bow, NE", amount: 5000 },
      { name: "David Briggs", location: "Scottsbluff, NE", amount: 5000 },
      { name: "Michael Cassling", location: "Omaha, NE", amount: 3500 },
      { name: "William Snodgrass", location: "North Platte, NE", amount: 2500 },
      { name: "Matt Rokowsky", location: "Jackson, NJ", amount: 1920 },
      { name: "Alan Erickson", location: "North Platte, NE", amount: 1000 },
      { name: "Dave Collins", location: "North Platte, NE", amount: 1000 },
      { name: "Robert Stefka", location: "North Platte, NE", amount: 1000 },
      { name: "Sandra Lundeen", location: "North Platte, NE", amount: 1000 },
      { name: "Jack Vetter", location: "Elkhorn, NE", amount: 500 },
    ],
  },
  "Danielle Conrad": {
    committeeName: "Conrad For Legislature",
    totalRaised: 265615,
    asOf: "2023\u20132026 NADC filings (cycle to date)",
    individualDonorCount: 64,
    individualAverage: 789,
    geography: {
      individual: { nebraska: 40111, outOfState: 10382 },
      corporate: { nebraska: 61530, outOfState: 36600 },
    },
    corporate: [
      { name: "Cannabis Factory", location: "Omaha, NE", amount: 6000 },
      { name: "Reynolds American INC. / Rai Services", location: "Winston Salem, NC", amount: 5500 },
      { name: "Horsemen'S Exposition & Racing INC. DBA Horsemens Park", location: "Omaha, NE", amount: 5500 },
      { name: "Nextera Energy Resources, LLC", location: "Juno Beach, FL", amount: 5000 },
      { name: "Altria Client Services, INC. (Va)", location: "Richmond, VA", amount: 5000 },
      { name: "International Assn Of Fire Fighters (Lincoln Fire Fighters Assn.) Local 644", location: "Lincoln, NE", amount: 4500 },
      { name: "Radcliffe & Associates (Radcliffe Gilbertson & Brady)", location: "Lincoln, NE", amount: 3000 },
      { name: "Centene Corporation (63105)", location: "St. Louis, MO", amount: 3000 },
      { name: "Panama Energy Center, LLC", location: "Juno Beach, FL", amount: 2500 },
      { name: "Rai Services  Company", location: "Winston Salem, NC", amount: 2500 },
    ],
    individual: [
      { name: "Susanne Shore", location: "Omaha, NE", amount: 15000 },
      { name: "Aimee Eicher", location: "Dodgeville, WI", amount: 9000 },
      { name: "Judy Eicher", location: "Lincoln, NE", amount: 3000 },
      { name: "Darla Zink", location: "Omaha, NE", amount: 3000 },
      { name: "Stephanie Nantkes", location: "Seward, NE", amount: 1250 },
      { name: "Deanna Hutchins", location: "Lincoln, NE", amount: 1000 },
      { name: "Kile Johnson", location: "Lincoln, NE", amount: 1000 },
      { name: "Allen Fredrickson", location: "Omaha, NE", amount: 1000 },
      { name: "Paul Schumacher", location: "Columbus, NE", amount: 1000 },
      { name: "Alison Plessman", location: "Los Angeles, CA", amount: 1000 },
    ],
  },
  "Patty Pansing Brooks": {
    committeeName: "Pansing Brooks For Legislature",
    totalRaised: 256696,
    asOf: "2023\u20132026 NADC filings (cycle to date)",
    individualDonorCount: 471,
    individualAverage: 413,
    geography: {
      individual: { nebraska: 187132, outOfState: 7351 },
      corporate: { nebraska: 9035, outOfState: 1000 },
    },
    corporate: [
      { name: "Reynolds American INC. / Rai Services", location: "Winston Salem, NC", amount: 1000 },
      { name: "Nebraska & Southwest Iowa Building & Construction Trades Council", location: "Omaha, NE", amount: 1000 },
      { name: "Radcliffe & Associates (Radcliffe Gilbertson & Brady)", location: "Lincoln, NE", amount: 923 },
      { name: "Catalyst Public Affairs (68508)", location: "Lincoln, NE", amount: 750 },
      { name: "Eickholt Law, LLC (Christopher L Eickholt)", location: "Lincoln, NE", amount: 600 },
      { name: "Nebraska Broadcasters Association INC.", location: "Omaha, NE", amount: 500 },
      { name: "Vincent Powers & Associates", location: "Lincoln, NE", amount: 500 },
      { name: "Teamsters Local 554 Political", location: "Omaha, NE", amount: 500 },
      { name: "Kissel Kohout Es Associates LLC", location: "Lincoln, NE", amount: 423 },
      { name: "Mueller Robak, LLC", location: "Lincoln, NE", amount: 423 },
    ],
    individual: [
      { name: "Christine Stone", location: "Lincoln, NE", amount: 6200 },
      { name: "Kile Johnson", location: "Lincoln, NE", amount: 5750 },
      { name: "Rhonda Seacrest", location: "Lincoln, NE", amount: 5500 },
      { name: "Susanne Shore", location: "Omaha, NE", amount: 5000 },
      { name: "John Brasch", location: "Lincoln, NE", amount: 5000 },
      { name: "Thomas Pansing Jr.", location: "Omaha, NE", amount: 5000 },
      { name: "Mary Campbell", location: "Lincoln, NE", amount: 5000 },
      { name: "Herb Friedman", location: "Lincoln, NE", amount: 5000 },
      { name: "Laura Acklie", location: "Lincoln, NE", amount: 5000 },
      { name: "Laurie Witters-Churchill", location: "Lincoln, NE", amount: 3500 },
    ],
  },
  "Rick Holdcroft": {
    committeeName: "Rick Holdcroft For Legislature District 36",
    totalRaised: 255326,
    asOf: "2023\u20132026 NADC filings (cycle to date)",
    individualDonorCount: 54,
    individualAverage: 1865,
    geography: {
      individual: { nebraska: 36210, outOfState: 66000 },
      corporate: { nebraska: 36850, outOfState: 26762 },
    },
    corporate: [
      { name: "Cox Communications", location: "Wichita, KS", amount: 4850 },
      { name: "Advanced Gaming Technologies", location: "Bellevue, NE", amount: 3500 },
      { name: "Hawkins Construction Company", location: "Omaha, NE", amount: 2500 },
      { name: "Charter Communications", location: "St Louis, MO", amount: 2500 },
      { name: "BNSF Railway Company", location: "Fort Worth, TX", amount: 2500 },
      { name: "Kissel Kohout Es Associates LLC", location: "Lincoln, NE", amount: 2500 },
      { name: "Great Plains Communications, INC.", location: "Blair, NE", amount: 2500 },
      { name: "Alliance Omaha Soccer LLC DBA Union Omaha", location: "Papillion, NE", amount: 2500 },
      { name: "Sv3", location: "Phoenix, AZ", amount: 2500 },
      { name: "Warhorse Gaming", location: "Winnebago, NE", amount: 2500 },
    ],
    individual: [
      { name: "Donald Crevier", location: "Irvine, CA", amount: 25000 },
      { name: "William Kent", location: "Fort Lauderdale, FL", amount: 20000 },
      { name: "William Ingram", location: "Palm Beach, FL", amount: 10000 },
      { name: "Arthur Dantchik", location: "Bala Cynwyd, PA", amount: 6000 },
      { name: "Travis Anderson", location: "Goshen, KY", amount: 5000 },
      { name: "Michael Cassling", location: "Omaha, NE", amount: 4000 },
      { name: "James Pillen", location: "Columbus, NE", amount: 2500 },
      { name: "William Harrold", location: "Springfield, NE", amount: 2000 },
      { name: "Charles Herbster", location: "Falls City, NE", amount: 1500 },
      { name: "Patrick Brennan", location: "Papillion, NE", amount: 1500 },
    ],
  },
  "Jess Goldoni": {
    committeeName: "Jess Goldoni For Legislature",
    totalRaised: 185684,
    asOf: "2023\u20132026 NADC filings (cycle to date)",
    individualDonorCount: 29,
    individualAverage: 2161,
    geography: {
      individual: { nebraska: 56655, outOfState: 6000 },
      corporate: { nebraska: 29806, outOfState: 0 },
    },
    corporate: [
      { name: "Planned Parenthood Advocates Of Nebraska", location: "Lincoln, NE", amount: 17406 },
      { name: "Nebraska & Southwest Iowa Building & Construction Trades Council", location: "Omaha, NE", amount: 5000 },
      { name: "Consolidated Companies, INC.", location: "Lincoln, NE", amount: 700 },
      { name: "Teamsters Local 554 Political", location: "Omaha, NE", amount: 500 },
      { name: "Cox Communications, INC.", location: "Omaha, NE", amount: 250 },
      { name: "Nebraska State AFL-CIO", location: "Lincoln, NE", amount: 250 },
      { name: "Radcliffe & Associates Trust Account", location: "Lincoln, NE", amount: 100 },
      { name: "Peetz & Company", location: "Lincoln, NE", amount: 100 },
      { name: "Lindsay Harr MacDonald", location: "Lincoln, NE", amount: 100 },
      { name: "Mueller Robak, LLC", location: "Lincoln, NE", amount: 100 },
    ],
    individual: [
      { name: "Dianne Lozier", location: "Omaha, NE", amount: 20000 },
      { name: "Donna Moragues", location: "Omaha, NE", amount: 10000 },
      { name: "Barbara Weitz", location: "Omaha, NE", amount: 10000 },
      { name: "Katie Weitz", location: "Omaha, NE", amount: 6435 },
      { name: "Sam Jacobs", location: "New York, NY", amount: 5000 },
      { name: "Susanne Shore", location: "Omaha, NE", amount: 3500 },
      { name: "Mary Ann Holland", location: "Omaha, NE", amount: 1000 },
      { name: "Danielle Conrad", location: "Lincoln, NE", amount: 1000 },
      { name: "Megan Hull", location: "Oakland, CA", amount: 1000 },
      { name: "Jeff Schlichting", location: "Omaha, NE", amount: 580 },
    ],
  },
  "Barry DeKay": {
    committeeName: "Rural Nebraskans For Barry Dekay",
    totalRaised: 179169,
    asOf: "2023\u20132026 NADC filings (cycle to date)",
    individualDonorCount: 33,
    individualAverage: 460,
    geography: {
      individual: { nebraska: 13966, outOfState: 1200 },
      corporate: { nebraska: 53748, outOfState: 52821 },
    },
    corporate: [
      { name: "Invenergy, LLC", location: "Chicago, IL", amount: 22000 },
      { name: "PAC Management Services, LLC", location: "Alexandria, VA", amount: 6000 },
      { name: "Warhorse Gaming LLC", location: "Winnebago, NE", amount: 5500 },
      { name: "Nextera Energy Resources, LLC", location: "Juno Beach, FL", amount: 5000 },
      { name: "Horsemen'S Exposition & Racing INC. DBA Horsemens Park", location: "Omaha, NE", amount: 5000 },
      { name: "Cox Communications", location: "Wichita, KS", amount: 4600 },
      { name: "Radcliffe & Associates (Radcliffe Gilbertson & Brady)", location: "Lincoln, NE", amount: 3042 },
      { name: "Peter Kiewit Sons' INC.", location: "Omaha, NE", amount: 3000 },
      { name: "Panama Energy Center, LLC", location: "Juno Beach, FL", amount: 2500 },
      { name: "Peetz & Company", location: "Lincoln, NE", amount: 2450 },
    ],
    individual: [
      { name: "Brent Dekay", location: "Conroe, TX", amount: 1200 },
      { name: "Timothy Gragert", location: "Creighton, NE", amount: 1000 },
      { name: "Ken Tusha", location: "Creighton, NE", amount: 1000 },
      { name: "Brian Hinkley", location: "Lincoln, NE", amount: 1000 },
      { name: "Lisa Dent", location: "Elkhorn, NE", amount: 1000 },
      { name: "Natalie Peetz", location: "Lincoln, NE", amount: 1000 },
      { name: "Michael Cassling", location: "Omaha, NE", amount: 1000 },
      { name: "Fred Meyer", location: "St Paul, NE", amount: 800 },
      { name: "Scott Fiedler", location: "Crofton, NE", amount: 800 },
      { name: "Wayne Heyen", location: "Lincoln, NE", amount: 800 },
    ],
  },
  "Cindy Maxwell-Ostdiek": {
    committeeName: "Friends Of Cindy Maxwell-Ostdiek",
    totalRaised: 168795,
    asOf: "2023\u20132026 NADC filings (cycle to date)",
    individualDonorCount: 43,
    individualAverage: 1181,
    geography: {
      individual: { nebraska: 39426, outOfState: 11351 },
      corporate: { nebraska: 36406, outOfState: 0 },
    },
    corporate: [
      { name: "Planned Parenthood Advocates Of Nebraska", location: "Lincoln, NE", amount: 15479 },
      { name: "Bold Alliance", location: "Doniphan, NE", amount: 5075 },
      { name: "I.B.E.W. Local Union No. 22 ( IBEW Local 22 )", location: "Omaha, NE", amount: 5000 },
      { name: "Generation V, INC.", location: "Lincoln, NE", amount: 500 },
      { name: "Teamsters Local 554 Political", location: "Omaha, NE", amount: 500 },
      { name: "Nebraska State Afl - Cio", location: "Lincoln, NE", amount: 250 },
    ],
    individual: [
      { name: "Dianne Lozier", location: "Omaha, NE", amount: 20000 },
      { name: "Katie Weitz", location: "Omaha, NE", amount: 5000 },
      { name: "Theresa Welch", location: "Corvallis, OR", amount: 3500 },
      { name: "Tim Fickenscher", location: "Omaha, NE", amount: 3400 },
      { name: "Carol Windrum", location: "Omaha, NE", amount: 2000 },
      { name: "Sara Paretsky", location: "Chicago, IL", amount: 1026 },
      { name: "Ali Khan", location: "Omaha, NE", amount: 1000 },
      { name: "Eric Niehans", location: "Minneapolis, MN", amount: 1000 },
      { name: "Sarah Kenney", location: "Newton Heights, MA", amount: 1000 },
      { name: "Elizabeth Whitten", location: "Brooklyn, NY", amount: 1000 },
    ],
  },
  "Cindy Johnson": {
    committeeName: "Cindy Johnson For Nebraska",
    totalRaised: 153751,
    asOf: "2023\u20132026 NADC filings (cycle to date)",
    individualDonorCount: 44,
    individualAverage: 1418,
    geography: {
      individual: { nebraska: 51350, outOfState: 11050 },
      corporate: { nebraska: 26200, outOfState: 7000 },
    },
    corporate: [
      { name: "Planned Parenthood Advocates Of Nebraska", location: "Lincoln, NE", amount: 14664 },
      { name: "Academy Of Doctors Of Audiology", location: "Frankfurt, KY", amount: 5000 },
      { name: "I.B.E.W. Local Union No. 22 ( IBEW Local 22 )", location: "Omaha, NE", amount: 5000 },
      { name: "Nebraska & Southwest Iowa Building & Construction Trades Council", location: "Omaha, NE", amount: 2500 },
      { name: "Altria Client Services, INC. (Va)", location: "Richmond, VA", amount: 2000 },
      { name: "Active Hearing Health LLC", location: "Omaha, NE", amount: 500 },
      { name: "Catalyst Public Affairs (68508)", location: "Lincoln, NE", amount: 500 },
      { name: "Warhorse Gaming LLC", location: "Winnebago, NE", amount: 500 },
      { name: "Horsemen'S Exposition & Racing INC. DBA Horsemens Park", location: "Omaha, NE", amount: 500 },
      { name: "Kissel Kohout Es Associates LLC", location: "Lincoln, NE", amount: 419 },
    ],
    individual: [
      { name: "Dianne Lozier", location: "Omaha, NE", amount: 20000 },
      { name: "Katie Weitz", location: "Omaha, NE", amount: 10000 },
      { name: "David Kohles", location: "Bellingham, WA", amount: 3000 },
      { name: "Sean Johnson", location: "Omaha, NE", amount: 3000 },
      { name: "Raoul Johnson", location: "Lincoln, NE", amount: 2500 },
      { name: "Teresa Welch", location: "Corvallis, OR", amount: 2500 },
      { name: "Richard Lombardi", location: "Lincoln, NE", amount: 1250 },
      { name: "Elizabeth Engel", location: "Omaha, NE", amount: 1100 },
      { name: "Roger Penzotti", location: "Omaha, NE", amount: 1000 },
      { name: "Don Bredhauer", location: "Omaha, NE", amount: 1000 },
    ],
  },
  "Teresa Ibach": {
    committeeName: "Teresa Ibach For Legislature",
    totalRaised: 147871,
    asOf: "2023\u20132026 NADC filings (cycle to date)",
    individualDonorCount: 48,
    individualAverage: 724,
    geography: {
      individual: { nebraska: 32703, outOfState: 2600 },
      corporate: { nebraska: 38815, outOfState: 32291 },
    },
    corporate: [
      { name: "Charter Communications", location: "St Louis, MO", amount: 6500 },
      { name: "Connie Lapaseotes, LTD", location: "Bridgeport, NE", amount: 5000 },
      { name: "La Vaca Cattle CO", location: "Littleton, CO", amount: 5000 },
      { name: "Cox Communications", location: "Wichita, KS", amount: 3814 },
      { name: "Kaapa Ethanol Holdings, LLC", location: "Kearney, NE", amount: 3500 },
      { name: "Centene Corporation (63105)", location: "St. Louis, MO", amount: 3000 },
      { name: "Consolidated Companies, INC.", location: "Lincoln, NE", amount: 2628 },
      { name: "Nextera Energy Resources, LLC", location: "Juno Beach, FL", amount: 2500 },
      { name: "Panama Energy Center, LLC", location: "Juno Beach, FL", amount: 2500 },
      { name: "B & L Foote Farms, LLC", location: "Imperial, NE", amount: 2500 },
    ],
    individual: [
      { name: "Jerry Adams", location: "Broken Bow, NE", amount: 10000 },
      { name: "Brad Foote", location: "Imperial, NE", amount: 7500 },
      { name: "Michael Cassling", location: "Omaha, NE", amount: 3500 },
      { name: "Arthur Dantchik", location: "Bala Cynwyd, PA", amount: 2500 },
      { name: "Paul Kenney", location: "Amherst, NE", amount: 1000 },
      { name: "Dan Hughes", location: "Venango, NE", amount: 500 },
      { name: "Al Svajgr", location: "Cozad, NE", amount: 500 },
      { name: "Leslie Marsh", location: "Kearney, NE", amount: 500 },
      { name: "Nanette Beattie", location: "Sumner, NE", amount: 500 },
      { name: "Shana Beattie", location: "Sumner, NE", amount: 500 },
    ],
  },
  "Shay Smith": {
    committeeName: "Shay For Nebraska",
    totalRaised: 133457,
    asOf: "2023\u20132026 NADC filings (cycle to date)",
    individualDonorCount: 43,
    individualAverage: 838,
    geography: {
      individual: { nebraska: 36805, outOfState: 1000 },
      corporate: { nebraska: 9489, outOfState: 2000 },
    },
    corporate: [
      { name: "Nebraska & Southwest Iowa Building & Construction Trades Council", location: "Omaha, NE", amount: 2500 },
      { name: "Altria Client Services, INC. (Va)", location: "Richmond, VA", amount: 2000 },
      { name: "Consolidated Companies, INC.", location: "Lincoln, NE", amount: 1068 },
      { name: "Donis Painting LLC", location: "Crete, NE", amount: 1000 },
      { name: "Kissel Kohout Es Associates LLC", location: "Lincoln, NE", amount: 718 },
      { name: "Johnson, Flodman, Guenzel & Widger", location: "Lincoln, NE", amount: 534 },
      { name: "Ehpv Companies (Big Red)", location: "Omaha, NE", amount: 500 },
      { name: "Kalkwarf & Smith Law Offices, LLC", location: "Crete, NE", amount: 500 },
      { name: "Nebraska State AFL-CIO", location: "Lincoln, NE", amount: 250 },
      { name: "Radcliffe & Associates (Radcliffe Gilbertson & Brady)", location: "Lincoln, NE", amount: 218 },
    ],
    individual: [
      { name: "Dianne Lozier", location: "Omaha, NE", amount: 10000 },
      { name: "James Meyers", location: "Crete, NE", amount: 1500 },
      { name: "Corey Wasserburger", location: "Lincoln, NE", amount: 1500 },
      { name: "Gerald Schmidt", location: "Jansen, NE", amount: 1500 },
      { name: "Jack Thompson", location: "Martell, NE", amount: 1250 },
      { name: "Vicky Johnson", location: "Lincoln, NE", amount: 1100 },
      { name: "Kathleen Neary", location: "Lincoln, NE", amount: 1000 },
      { name: "Lorene Horky", location: "Crete, NE", amount: 1000 },
      { name: "Lynn McCaig", location: "Lincoln, NE", amount: 1000 },
      { name: "Kile Johnson", location: "Lincoln, NE", amount: 1000 },
    ],
  },
  "SuAnn Witt": {
    committeeName: "Suann Witt For Nebraska",
    totalRaised: 129668,
    asOf: "2023\u20132026 NADC filings (cycle to date)",
    individualDonorCount: 21,
    individualAverage: 1580,
    geography: {
      individual: { nebraska: 28375, outOfState: 4808 },
      corporate: { nebraska: 7429, outOfState: 0 },
    },
    corporate: [
      { name: "Planned Parenthood Advocates Of Nebraska", location: "Lincoln, NE", amount: 6679 },
      { name: "Kissel Kohout Es Associates LLC", location: "Lincoln, NE", amount: 250 },
      { name: "Nebraska State AFL-CIO", location: "Lincoln, NE", amount: 250 },
      { name: "Catalyst Public Affairs (68508)", location: "Lincoln, NE", amount: 250 },
    ],
    individual: [
      { name: "Dianne Lozier", location: "Omaha, NE", amount: 20000 },
      { name: "Teresa Welch", location: "Corvallis, OR", amount: 3500 },
      { name: "Edward Taylor", location: "Omaha, NE", amount: 1250 },
      { name: "Bret Brasfield", location: "Papillion, NE", amount: 1000 },
      { name: "Lisa Kuechenmeister", location: "La Vista, NE", amount: 1000 },
      { name: "Katie Weitz", location: "Omaha, NE", amount: 1000 },
      { name: "Susanne Shore", location: "Omaha, NE", amount: 1000 },
      { name: "Christine Clerc", location: "Bellevue, NE", amount: 500 },
      { name: "Fred Tafoya", location: "Papillion, NE", amount: 500 },
      { name: "John Fletcher", location: "Omaha, NE", amount: 500 },
    ],
  },
  "Merv Riepe": {
    committeeName: "Riepe For Nebraska",
    totalRaised: 128027,
    asOf: "2023\u20132026 NADC filings (cycle to date)",
    individualDonorCount: 12,
    individualAverage: 682,
    geography: {
      individual: { nebraska: 8681, outOfState: 500 },
      corporate: { nebraska: 32913, outOfState: 26562 },
    },
    corporate: [
      { name: "Centene Corporation (63105)", location: "St. Louis, MO", amount: 4000 },
      { name: "Kissel Kohout Es Associates LLC", location: "Lincoln, NE", amount: 2124 },
      { name: "Cox Communications", location: "Wichita, KS", amount: 2000 },
      { name: "Molina Healthcare INC", location: "Long Beach, CA", amount: 2000 },
      { name: "Novo Nordisk", location: "Plainsboro, NJ", amount: 2000 },
      { name: "Hands Of Heartland, LLC", location: "Bellevue, NE", amount: 2000 },
      { name: "Pacific Life Insurance Company", location: "Newport Beach, VA", amount: 2000 },
      { name: "Nebraska Chamber Of Commerce And Industry", location: "Lincoln, NE", amount: 1750 },
      { name: "Cox Communications, INC.", location: "Omaha, NE", amount: 1561 },
      { name: "Kaapa Ethanol Holdings, LLC", location: "Kearney, NE", amount: 1500 },
    ],
    individual: [
      { name: "John Luckasen", location: "Omaha, NE", amount: 1500 },
      { name: "Jack Vetter", location: "Elkhorn, NE", amount: 1000 },
      { name: "Michael Cassling", location: "Omaha, NE", amount: 1000 },
      { name: "William Cutler", location: "Omaha, NE", amount: 1000 },
      { name: "Jay Noddle", location: "Omaha, NE", amount: 1000 },
      { name: "John Murante", location: "Omaha, NE", amount: 500 },
      { name: "Robert Hibbard", location: "Oshoto, WY", amount: 500 },
      { name: "Paul Schumacher", location: "Columbus, NE", amount: 500 },
      { name: "Matthew Williams", location: "Gothenburg, NE", amount: 500 },
      { name: "Michael Tierney", location: "Ralston, NE", amount: 500 },
    ],
  },
  "Jana Hughes": {
    committeeName: "Jana Hughes For Legislature",
    totalRaised: 127790,
    asOf: "2023\u20132026 NADC filings (cycle to date)",
    individualDonorCount: 114,
    individualAverage: 272,
    geography: {
      individual: { nebraska: 30433, outOfState: 1100 },
      corporate: { nebraska: 27161, outOfState: 19084 },
    },
    corporate: [
      { name: "Nextera Energy Resources, LLC", location: "Juno Beach, FL", amount: 5000 },
      { name: "Panama Energy Center, LLC", location: "Juno Beach, FL", amount: 2500 },
      { name: "Sv3", location: "Phoenix, AZ", amount: 2500 },
      { name: "Nebraska Broadcasters Association", location: "Omaha, NE", amount: 2499 },
      { name: "Kissel Kohout Es Associates LLC", location: "Lincoln, NE", amount: 2109 },
      { name: "Radcliffe & Associates (Radcliffe Gilbertson & Brady)", location: "Lincoln, NE", amount: 1608 },
      { name: "Centene Corporation (63105)", location: "St. Louis, MO", amount: 1500 },
      { name: "Rai Services  Company", location: "Winston Salem, NC", amount: 1500 },
      { name: "Alliance Omaha Soccer LLC DBA Union Omaha", location: "Papillion, NE", amount: 1500 },
      { name: "Consolidated Companies, INC.", location: "Lincoln, NE", amount: 1408 },
    ],
    individual: [
      { name: "Jim Spahr", location: "York, NE", amount: 2690 },
      { name: "Christopher Wolfe", location: "Omaha, NE", amount: 1000 },
      { name: "James Schultz", location: "Lincoln, NE", amount: 1000 },
      { name: "Jim Daws", location: "Seward, NE", amount: 1000 },
      { name: "Matt Stryson", location: "Seward, NE", amount: 1000 },
      { name: "Kelly Driewer", location: "York, NE", amount: 1000 },
      { name: "Kristie Holoch", location: "York, NE", amount: 1000 },
      { name: "Michael Cassling", location: "Omaha, NE", amount: 1000 },
      { name: "Lauren Cooper", location: "Tampa, FL", amount: 1000 },
      { name: "Mark Kolterman", location: "Seward, NE", amount: 600 },
    ],
  },
  "Brian Hardin": {
    committeeName: "Hardin For Legislature",
    totalRaised: 125031,
    asOf: "2023\u20132026 NADC filings (cycle to date)",
    individualDonorCount: 9,
    individualAverage: 1746,
    geography: {
      individual: { nebraska: 8650, outOfState: 7061 },
      corporate: { nebraska: 30689, outOfState: 19629 },
    },
    corporate: [
      { name: "Charter Communications, INC.", location: "Lincoln, NE", amount: 6000 },
      { name: "Centene Corporation (63105)", location: "St. Louis, MO", amount: 6000 },
      { name: "Molina Healthcare INC", location: "Long Beach, CA", amount: 2500 },
      { name: "Kissel Kohout Es Associates LLC", location: "Lincoln, NE", amount: 2304 },
      { name: "Novo Nordisk", location: "Plainsboro, NJ", amount: 2000 },
      { name: "Pacific Life Insurance Company", location: "Newport Beach, VA", amount: 2000 },
      { name: "Husker Gaming LLC", location: "Bolingbrook, IL", amount: 2000 },
      { name: "Nebraska Horsemens & Benevolent Protective Assn. (HBPA)", location: "Lincoln, NE", amount: 1613 },
      { name: "Alliance Omaha Soccer LLC DBA Union Omaha", location: "Papillion, NE", amount: 1500 },
      { name: "Consolidated Companies, INC.", location: "Lincoln, NE", amount: 1361 },
    ],
    individual: [
      { name: "Arthur Dantchik", location: "Bala Cynwyd, PA", amount: 6000 },
      { name: "David Briggs", location: "Scottsbluff, NE", amount: 5000 },
      { name: "Michael Cassling", location: "Omaha, NE", amount: 2500 },
      { name: "Paul Doucette", location: "Salinas, PR", amount: 1061 },
      { name: "Zac Karpf", location: "Gering, NE", amount: 500 },
      { name: "Heath Mello", location: "Omaha, NE", amount: 350 },
      { name: "Martin Liphardt", location: "Lincoln, NE", amount: 100 },
      { name: "Seth Voyles", location: "Elkhorn, NE", amount: 100 },
      { name: "Patricia Ohmberger", location: "Lincoln, NE", amount: 100 },
    ],
  },
  "Darin Tompkins": {
    committeeName: "Tompkins For Nebraska",
    totalRaised: 120166,
    asOf: "2023\u20132026 NADC filings (cycle to date)",
    individualDonorCount: 17,
    individualAverage: 898,
    geography: {
      individual: { nebraska: 7558, outOfState: 7700 },
      corporate: { nebraska: 27600, outOfState: 0 },
    },
    corporate: [
      { name: "Dianne S Lozier Trust", location: "Omaha, NE", amount: 20000 },
      { name: "I.B.E.W. Local Union No. 22 ( IBEW Local 22 )", location: "Omaha, NE", amount: 5000 },
      { name: "Nebraska & Southwest Iowa Building & Construction Trades Council", location: "Omaha, NE", amount: 2500 },
      { name: "American Communications Group, INC.", location: "Lincoln, NE", amount: 100 },
    ],
    individual: [
      { name: "Sanford Schuster", location: "Mankato, MN", amount: 2200 },
      { name: "Barb Tompkins", location: "Webster, SD", amount: 2000 },
      { name: "Teresa Welch", location: "Corvallis, OR", amount: 2000 },
      { name: "Joanne Ferguson Cavanaugh", location: "Papillion, NE", amount: 1200 },
      { name: "Kishla Askins", location: "Omaha, NE", amount: 1000 },
      { name: "Katie Weitz", location: "Omaha, NE", amount: 1000 },
      { name: "Sam Walton", location: "Carbondale, CO", amount: 1000 },
      { name: "Christine Clerc", location: "Bellevue, NE", amount: 850 },
      { name: "Elizabeth Tompkins", location: "Papillion, NE", amount: 508 },
      { name: "Victor Rountree", location: "Bellevue, NE", amount: 500 },
    ],
  },
  "Taylor Royal": {
    committeeName: "Taylor Royal For Legislature",
    totalRaised: 109126,
    asOf: "2023\u20132026 NADC filings (cycle to date)",
    individualDonorCount: 41,
    individualAverage: 1068,
    geography: {
      individual: { nebraska: 41800, outOfState: 2500 },
      corporate: { nebraska: 12101, outOfState: 250 },
    },
    corporate: [
      { name: "Hawkins Construction Company", location: "Omaha, NE", amount: 2000 },
      { name: "Great Plains Communications, INC.", location: "Blair, NE", amount: 1575 },
      { name: "Union Pacific Railroad Company", location: "Omaha, NE", amount: 1000 },
      { name: "Kissel Kohout Es Associates LLC", location: "Lincoln, NE", amount: 825 },
      { name: "Consolidated Companies, INC.", location: "Lincoln, NE", amount: 575 },
      { name: "Radcliffe & Associates (Radcliffe Gilbertson & Brady)", location: "Lincoln, NE", amount: 575 },
      { name: "H & H Automotive", location: "Omaha, NE", amount: 500 },
      { name: "Wdd INC DBA Pella Windows & Doors Of Omaha/Lincoln", location: "Omaha, NE", amount: 500 },
      { name: "Cp Strategies, LLC", location: "Lincoln, NE", amount: 325 },
      { name: "Burlington Capital, LLC", location: "Omaha, NE", amount: 250 },
    ],
    individual: [
      { name: "Michael Cassling", location: "Omaha, NE", amount: 10000 },
      { name: "Trish Royal", location: "Bennington, NE", amount: 6000 },
      { name: "Steven George", location: "Elkhorn, NE", amount: 2500 },
      { name: "Robert Milligan", location: "Omaha, NE", amount: 2500 },
      { name: "Fred Hunzeker", location: "Omaha, NE", amount: 2500 },
      { name: "Justin Peterson", location: "Washington, DC", amount: 2500 },
      { name: "Dana Bradford", location: "Omaha, NE", amount: 1500 },
      { name: "Michael Faust", location: "Omaha, NE", amount: 1000 },
      { name: "Mary Harper", location: "Bennington, NE", amount: 1000 },
      { name: "Charles Herbster", location: "Falls City, NE", amount: 1000 },
    ],
  },
  "Josh Livingston": {
    committeeName: "Livingston For Nebraska",
    totalRaised: 107310,
    asOf: "2023\u20132026 NADC filings (cycle to date)",
    individualDonorCount: 25,
    individualAverage: 2863,
    geography: {
      individual: { nebraska: 11150, outOfState: 62925 },
      corporate: { nebraska: 850, outOfState: 15000 },
    },
    corporate: [
      { name: "Livingston Holdings, INC", location: "Walnut Creek, CA", amount: 15000 },
      { name: "Devotion Law PC LLO", location: "Omaha, NE", amount: 500 },
      { name: "Kissel Kohout Es Associates LLC", location: "Lincoln, NE", amount: 350 },
    ],
    individual: [
      { name: "Randall Livingston", location: "Summerland Key, FL", amount: 47000 },
      { name: "Jerrold Livingston", location: "Walnut Creek, CA", amount: 6000 },
      { name: "Sherri Steffens", location: "Waverly, NE", amount: 4500 },
      { name: "Cassandra Whetstone", location: "McAllen, TX", amount: 2600 },
      { name: "Joanna Cox", location: "McKinney, TX", amount: 2525 },
      { name: "Loretta Stagnitto", location: "Los Gatos, CA", amount: 1500 },
      { name: "Rhonda Willens", location: "Pleasanton, CA", amount: 1000 },
      { name: "Matthew Johnson", location: "Omaha, NE", amount: 1000 },
      { name: "Jake Ricci", location: "Los Gatos, CA", amount: 500 },
      { name: "Jane Raybould", location: "Lincoln, NE", amount: 500 },
    ],
  },
  "Erin Feichtinger": {
    committeeName: "Erin For Nebraska",
    totalRaised: 106895,
    asOf: "2023\u20132026 NADC filings (cycle to date)",
    individualDonorCount: 34,
    individualAverage: 1550,
    geography: {
      individual: { nebraska: 50462, outOfState: 4850 },
      corporate: { nebraska: 8756, outOfState: 500 },
    },
    corporate: [
      { name: "I.B.E.W. Local Union No. 22 ( IBEW Local 22 )", location: "Omaha, NE", amount: 5000 },
      { name: "One Percent Productions, LLC", location: "Omaha, NE", amount: 1406 },
      { name: "Nebraska & Southwest Iowa Building & Construction Trades Council", location: "Omaha, NE", amount: 1000 },
      { name: "Kissel Kohout Es Associates LLC", location: "Lincoln, NE", amount: 500 },
      { name: "American Communications Group, INC.", location: "Lincoln, NE", amount: 500 },
      { name: "Husch Blackwell Strategies", location: "Jefferson City, MO", amount: 500 },
      { name: "Eickholt Law, LLC (Christopher L Eickholt)", location: "Lincoln, NE", amount: 350 },
    ],
    individual: [
      { name: "Barbara Weitz", location: "Omaha, NE", amount: 25000 },
      { name: "Jill Johnson", location: "Omaha, NE", amount: 3093 },
      { name: "Katie Weitz", location: "Omaha, NE", amount: 3050 },
      { name: "Michele Ernst", location: "Elkhorn, NE", amount: 2500 },
      { name: "Daniel McCarthy", location: "Omaha, NE", amount: 1500 },
      { name: "Daniel Dougherty", location: "Omaha, NE", amount: 1250 },
      { name: "Patrick Cavanaugh", location: "Omaha, NE", amount: 1250 },
      { name: "Katie Fiandt", location: "Omaha, NE", amount: 1200 },
      { name: "Lane Phillips", location: "Omaha, NE", amount: 1150 },
      { name: "Leann Romero", location: "Kansas City, MO", amount: 1000 },
    ],
  },
  "Bill Bowes": {
    committeeName: "Citizens For Bill Bowes",
    totalRaised: 102618,
    asOf: "2023\u20132026 NADC filings (cycle to date)",
    individualDonorCount: 146,
    individualAverage: 430,
    geography: {
      individual: { nebraska: 38975, outOfState: 23825 },
      corporate: { nebraska: 15300, outOfState: 0 },
    },
    corporate: [
      { name: "Froehlich Investments, L.L.C.", location: "Lavista, NE", amount: 3000 },
      { name: "Holiday Lighting Management, LLC", location: "Omaha, NE", amount: 2500 },
      { name: "Artisan Stone Company, INC.", location: "Omaha, NE", amount: 2500 },
      { name: "Bloom Dance Studio, LLC", location: "Omaha, NE", amount: 2400 },
      { name: "Alliance Omaha Soccer LLC DBA Union Omaha", location: "Papillion, NE", amount: 1000 },
      { name: "Morrow & Associates, INC.", location: "Omaha, NE", amount: 825 },
      { name: "E & A Consulting Group, INC.", location: "Omaha, NE", amount: 500 },
      { name: "Firefighters On The Move", location: "Papillion, NE", amount: 500 },
      { name: "Radcliffe & Associates (Radcliffe Gilbertson & Brady)", location: "Lincoln, NE", amount: 300 },
      { name: "Bellino Fireworks, INC.", location: "Papillion, NE", amount: 250 },
    ],
    individual: [
      { name: "Justin Peterson", location: "Washington, DC", amount: 12500 },
      { name: "Gerald Torczon", location: "Omaha, NE", amount: 5000 },
      { name: "David Harrig", location: "Gretna, NE", amount: 5000 },
      { name: "Alan Judge", location: "Gurley, AL", amount: 4500 },
      { name: "Daniel Claxton", location: "Valley, NE", amount: 4000 },
      { name: "Donald Schenzel", location: "Casselberry, FL", amount: 1750 },
      { name: "Alexandria Ross", location: "Omaha, NE", amount: 1200 },
      { name: "Frank Matter", location: "Papillion, NE", amount: 1000 },
      { name: "Robert Gottsch", location: "Papillion, NE", amount: 1000 },
      { name: "Charles Herbster", location: "Falls City, NE", amount: 1000 },
    ],
  },
  "Dean Helmick": {
    committeeName: "Helmick For Legislature",
    totalRaised: 94910,
    asOf: "2023\u20132026 NADC filings (cycle to date)",
    individualDonorCount: 131,
    individualAverage: 375,
    geography: {
      individual: { nebraska: 42289, outOfState: 6895 },
      corporate: { nebraska: 9150, outOfState: 1600 },
    },
    corporate: [
      { name: "Corn Growers State Bank", location: "Murdock, NE", amount: 1000 },
      { name: "Vireo Resources", location: "Madison, TN", amount: 1000 },
      { name: "Kmv Properties, LLC", location: "Nebraska City, NE", amount: 1000 },
      { name: "Alliance Omaha Soccer LLC DBA Union Omaha", location: "Papillion, NE", amount: 1000 },
      { name: "J Westling & CO., LLC", location: "Elkhorn, NE", amount: 1000 },
      { name: "Great Plains Communications, INC.", location: "Blair, NE", amount: 1000 },
      { name: "Kissel Kohout Es Associates LLC", location: "Lincoln, NE", amount: 750 },
      { name: "Catalyst Public Affairs (68508)", location: "Lincoln, NE", amount: 500 },
      { name: "Ash Grove Cement Company", location: "Overland Park, KS", amount: 500 },
      { name: "Consolidated Companies, INC.", location: "Lincoln, NE", amount: 500 },
    ],
    individual: [
      { name: "J Peter (Pete) Ricketts", location: "Omaha, NE", amount: 10000 },
      { name: "Carlene Ostrander", location: "Avoca, NE", amount: 4900 },
      { name: "Mary Jo Mougey", location: "Plattsmouth, NE", amount: 2200 },
      { name: "Derek Helmick", location: "Auburn, NE", amount: 2012 },
      { name: "Duane Murdoch", location: "Murray, NE", amount: 2000 },
      { name: "Rich Dreesman", location: "Plattsmouth, NE", amount: 1000 },
      { name: "John Carozza", location: "Bellevue, NE", amount: 1000 },
      { name: "Matthew Hicks", location: "Norfolk, NE", amount: 1000 },
      { name: "Richard Clements", location: "Elmwood, NE", amount: 1000 },
      { name: "Mark Faulkner", location: "Nashville, TN", amount: 1000 },
    ],
  },
  "Patrick Leahy": {
    committeeName: "Leahy For Nebraska",
    totalRaised: 91526,
    asOf: "2023\u20132026 NADC filings (cycle to date)",
    individualDonorCount: 21,
    individualAverage: 973,
    geography: {
      individual: { nebraska: 18425, outOfState: 2000 },
      corporate: { nebraska: 5376, outOfState: 1000 },
    },
    corporate: [
      { name: "Husch Blackwell LLP", location: "St Louis, MO", amount: 1000 },
      { name: "Kissel Kohout Es Associates LLC", location: "Lincoln, NE", amount: 669 },
      { name: "Consolidated Companies, INC.", location: "Lincoln, NE", amount: 569 },
      { name: "American Communications Group, INC.", location: "Lincoln, NE", amount: 569 },
      { name: "Oci Insurance & Financial Services, INC.", location: "Elkhorn, NE", amount: 500 },
      { name: "Gretna Sanitation, INC.", location: "Springfield, NE", amount: 500 },
      { name: "Mueller Robak, LLC", location: "Lincoln, NE", amount: 469 },
      { name: "Kelley Plucker, LLC", location: "Omaha, NE", amount: 269 },
      { name: "Catalyst Public Affairs (68508)", location: "Lincoln, NE", amount: 250 },
      { name: "Nebraska Strategies", location: "Lincoln, NE", amount: 250 },
    ],
    individual: [
      { name: "Beverly Kracher", location: "Papillion, NE", amount: 3000 },
      { name: "Dale Gubbels", location: "Papillion, NE", amount: 3000 },
      { name: "Katie Weitz", location: "Omaha, NE", amount: 2500 },
      { name: "Joseph Hebenstreit", location: "Omaha, NE", amount: 2000 },
      { name: "Jordan Hasan", location: "Omaha, NE", amount: 1000 },
      { name: "John Deboer", location: "Omaha, NE", amount: 1000 },
      { name: "David Newman", location: "Papillion, NE", amount: 1000 },
      { name: "Jon Stuehm", location: "Omaha, NE", amount: 1000 },
      { name: "Sam Walton", location: "Carbondale, CO", amount: 1000 },
      { name: "NIC Prenger", location: "Omaha, NE", amount: 500 },
    ],
  },
  "Mark Schoenrock": {
    committeeName: "Schoenrock For Legislature",
    totalRaised: 83714,
    asOf: "2023\u20132026 NADC filings (cycle to date)",
    individualDonorCount: 74,
    individualAverage: 248,
    geography: {
      individual: { nebraska: 18485, outOfState: 150 },
      corporate: { nebraska: 17541, outOfState: 100 },
    },
    corporate: [
      { name: "Westin Foods INC", location: "Fairbury, NE", amount: 3500 },
      { name: "Newton Family, LLC C/O Dick Newton Trustee", location: "Fairbury, NE", amount: 1500 },
      { name: "Great Plains Communications, INC.", location: "Blair, NE", amount: 1102 },
      { name: "Endicott Clay Products Company", location: "Endicott, NE", amount: 1000 },
      { name: "Dean Roelfs Farms", location: "Diller, NE", amount: 1000 },
      { name: "First Tri-County Bank", location: "Plymouth, NE", amount: 1000 },
      { name: "Alliance Omaha Soccer LLC DBA Union Omaha", location: "Papillion, NE", amount: 1000 },
      { name: "More Than Hardware, INC DBA Crete Ace Hardware", location: "Crete, NE", amount: 1000 },
      { name: "J Westling & CO., LLC", location: "Elkhorn, NE", amount: 1000 },
      { name: "Cp Strategies, LLC", location: "Lincoln, NE", amount: 702 },
    ],
    individual: [
      { name: "Lyle Katz", location: "Steele City, NE", amount: 1000 },
      { name: "Joshua Skavdahl", location: "Harrison, NE", amount: 1000 },
      { name: "Gerald Geiger", location: "Exeter, NE", amount: 1000 },
      { name: "Brad Christian", location: "Clatonia, NE", amount: 700 },
      { name: "Cody Moyer", location: "Fairbury, NE", amount: 500 },
      { name: "William Williams", location: "Omaha, NE", amount: 500 },
      { name: "Chris Roth", location: "Deshler, NE", amount: 500 },
      { name: "Shauna Mariska", location: "Belvidere, NE", amount: 500 },
      { name: "Jerry Catlett", location: "Bruning, NE", amount: 500 },
      { name: "Renee Dowdy", location: "Fairbury, NE", amount: 500 },
    ],
  },
  "Loren Lippincott": {
    committeeName: "Nebraskans For Loren Lippincott",
    totalRaised: 82995,
    asOf: "2023\u20132026 NADC filings (cycle to date)",
    individualDonorCount: 68,
    individualAverage: 416,
    geography: {
      individual: { nebraska: 19766, outOfState: 9600 },
      corporate: { nebraska: 31270, outOfState: 16627 },
    },
    corporate: [
      { name: "Kaapa Ethanol Holdings, LLC", location: "Kearney, NE", amount: 3500 },
      { name: "Centene Corporation (63105)", location: "St. Louis, MO", amount: 3500 },
      { name: "Charter Communications", location: "St Louis, MO", amount: 3500 },
      { name: "Kissel Kohout Es Associates LLC", location: "Lincoln, NE", amount: 1534 },
      { name: "Consolidated Companies, INC.", location: "Lincoln, NE", amount: 1506 },
      { name: "BNSF Railway Company", location: "Fort Worth, TX", amount: 1500 },
      { name: "Alliance Omaha Soccer LLC DBA Union Omaha", location: "Papillion, NE", amount: 1500 },
      { name: "Unitedhealth Group INC (20004)", location: "Washington, DC", amount: 1250 },
      { name: "Mueller Robak, LLC", location: "Lincoln, NE", amount: 1237 },
      { name: "Aurora Cooperative", location: "Aurora, NE", amount: 1000 },
    ],
    individual: [
      { name: "Arthur Dantchik", location: "Bala Cynwyd, PA", amount: 6000 },
      { name: "Phillip Torrison", location: "Omaha, NE", amount: 3298 },
      { name: "James Pillen", location: "Columbus, NE", amount: 2500 },
      { name: "Larry Stoney", location: "Phoenix, AZ", amount: 2000 },
      { name: "Daniel Thayer", location: "Grand Island, NE", amount: 1500 },
      { name: "Norman Krug", location: "Central City, NE", amount: 1500 },
      { name: "Sue Krug", location: "Central City, NE", amount: 1250 },
      { name: "Glenn Larson", location: "Central City, NE", amount: 1000 },
      { name: "Gregory Senkbile", location: "Central City, NE", amount: 550 },
      { name: "Chris Bonness", location: "Overland Park, KS", amount: 500 },
    ],
  },
  "Caitlin Knutson": {
    committeeName: "Knutson For Legislature",
    totalRaised: 77356,
    asOf: "2023\u20132026 NADC filings (cycle to date)",
    individualDonorCount: 21,
    individualAverage: 840,
    geography: {
      individual: { nebraska: 6394, outOfState: 11750 },
      corporate: { nebraska: 25000, outOfState: 0 },
    },
    corporate: [
      { name: "International Assn Of Fire Fighters (Lincoln Fire Fighters Assn.) Local 644", location: "Lincoln, NE", amount: 10000 },
    ],
    individual: [
      { name: "Sam Jacobs", location: "New York, NY", amount: 5000 },
      { name: "W. Pete Welch", location: "Washington, DC", amount: 2250 },
      { name: "Tim Judge", location: "Lincoln, NE", amount: 1200 },
      { name: "Jeffrey Judge", location: "Tuscon, AZ", amount: 1000 },
      { name: "Paul Knutson", location: "Fargo, ND", amount: 1000 },
      { name: "Susanne Shore", location: "Omaha, NE", amount: 1000 },
      { name: "Kay Judge", location: "Tucson, AZ", amount: 800 },
      { name: "Danielle Conrad", location: "Lincoln, NE", amount: 700 },
      { name: "Mary Jo Judge", location: "Lincoln, NE", amount: 626 },
      { name: "Kathleen Wingard", location: "Lincoln, NE", amount: 500 },
    ],
  },
  "Rebecca Rens": {
    committeeName: "Rebecca For Nebraska",
    totalRaised: 73593,
    asOf: "2023\u20132026 NADC filings (cycle to date)",
    individualDonorCount: 29,
    individualAverage: 978,
    geography: {
      individual: { nebraska: 28231, outOfState: 260 },
      corporate: { nebraska: 7111, outOfState: 100 },
    },
    corporate: [
      { name: "Alliance Omaha Soccer LLC DBA Union Omaha", location: "Papillion, NE", amount: 2500 },
      { name: "Hawkins Construction Company", location: "Omaha, NE", amount: 2000 },
      { name: "J Westling & CO., LLC", location: "Elkhorn, NE", amount: 1000 },
      { name: "Ehpv Companies (Big Red)", location: "Omaha, NE", amount: 500 },
      { name: "Kissel Kohout Es Associates LLC", location: "Lincoln, NE", amount: 250 },
      { name: "The Sullivan Group", location: "Omaha, NE", amount: 100 },
      { name: "Mueller Robak, LLC", location: "Lincoln, NE", amount: 100 },
      { name: "Zulkoski Weber, LLC", location: "Lincoln, NE", amount: 100 },
      { name: "Cp Strategies, LLC", location: "Lincoln, NE", amount: 100 },
      { name: "Radcliffe & Associates (Radcliffe Gilbertson & Brady)", location: "Lincoln, NE", amount: 100 },
    ],
    individual: [
      { name: "Charles Herbster", location: "Falls City, NE", amount: 11000 },
      { name: "Michael Cassling", location: "Omaha, NE", amount: 5000 },
      { name: "Fred Hunzeker", location: "Elkhorn, NE", amount: 3000 },
      { name: "Michael Smith", location: "Bennington, NE", amount: 1000 },
      { name: "Mike Faust", location: "Omaha, NE", amount: 1000 },
      { name: "John Marburger", location: "Omaha, NE", amount: 520 },
      { name: "Harold Daub", location: "Omaha, NE", amount: 500 },
      { name: "Wallace Johnson", location: "Omaha, NE", amount: 500 },
      { name: "Mary Harper", location: "Bennington, NE", amount: 500 },
      { name: "Carole Julian", location: "Omaha, NE", amount: 500 },
    ],
  },
  "Nate Ostdiek": {
    committeeName: "Nate Ostdiek For Nebraska Legislature",
    totalRaised: 70430,
    asOf: "2023\u20132026 NADC filings (cycle to date)",
    individualDonorCount: 12,
    individualAverage: 2015,
    geography: {
      individual: { nebraska: 19175, outOfState: 5000 },
      corporate: null,
    },
    corporate: [
    ],
    individual: [
      { name: "Barbara Weitz", location: "Omaha, NE", amount: 11500 },
      { name: "Sam Jacobs", location: "New York, NY", amount: 5000 },
      { name: "Zoe Miller", location: "Omaha, NE", amount: 1925 },
      { name: "Will Ostdiek", location: "Omaha, NE", amount: 1250 },
      { name: "Denise Powell", location: "Omaha, NE", amount: 1000 },
      { name: "Carol Gilbert", location: "Omaha, NE", amount: 600 },
      { name: "Mary Jo Langdon", location: "Omaha, NE", amount: 600 },
      { name: "Victor Rountree", location: "Bellevue, NE", amount: 500 },
      { name: "Thomas Egan", location: "Omaha, NE", amount: 500 },
      { name: "Stephen Molini", location: "Omaha, NE", amount: 500 },
    ],
  },
  "Tim Anderson": {
    committeeName: "Tim Anderson For Legislature",
    totalRaised: 69532,
    asOf: "2023\u20132026 NADC filings (cycle to date)",
    individualDonorCount: 33,
    individualAverage: 1268,
    geography: {
      individual: { nebraska: 37700, outOfState: 4500 },
      corporate: { nebraska: 6500, outOfState: 0 },
    },
    corporate: [
      { name: "Hawkins Construction Company", location: "Omaha, NE", amount: 2000 },
      { name: "George Brothers INC", location: "Sutton, NE", amount: 1200 },
      { name: "Unified Ag Solutions", location: "Omaha, NE", amount: 1000 },
      { name: "Neuerburg Trucking INC", location: "Fairbury, NE", amount: 1000 },
      { name: "V6 Farms", location: "Clay Center, NE", amount: 500 },
      { name: "A & L Plumbing And Heating, LLC", location: "Sutton, NE", amount: 300 },
      { name: "Kissel Kohout Es Associates LLC", location: "Lincoln, NE", amount: 250 },
      { name: "Consolidated Companies, INC.", location: "Lincoln, NE", amount: 250 },
    ],
    individual: [
      { name: "Bill Gerber", location: "Omaha, NE", amount: 10000 },
      { name: "Carl Elting", location: "Edgar, NE", amount: 5000 },
      { name: "Lynne Baldwin", location: "Omaha, NE", amount: 5000 },
      { name: "Justin Peterson", location: "Washington, DC", amount: 2500 },
      { name: "Peter Mayberry", location: "Valley, NE", amount: 2000 },
      { name: "Fred Hunzeker", location: "Elkhorn, NE", amount: 1500 },
      { name: "Joseph Kustelski", location: "Nashville, TN", amount: 1000 },
      { name: "Jeff Ortmeier", location: "Omaha, NE", amount: 1000 },
      { name: "Robert Anderson", location: "Ong, NE", amount: 1000 },
      { name: "Leslie Anderson", location: "Ong, NE", amount: 1000 },
    ],
  },
  "Ted Japp": {
    committeeName: "Ted Japp For Legislature",
    totalRaised: 62694,
    asOf: "2023\u20132026 NADC filings (cycle to date)",
    individualDonorCount: 14,
    individualAverage: 1611,
    geography: {
      individual: { nebraska: 15051, outOfState: 7500 },
      corporate: { nebraska: 8931, outOfState: 0 },
    },
    corporate: [
      { name: "Nebraska Chiropractic Physicians Association, INC", location: "Omaha, NE", amount: 4000 },
      { name: "Japp Brother Grading", location: "Kennard, NE", amount: 1000 },
      { name: "Mohrview Farm INC", location: "Omaha, NE", amount: 1000 },
      { name: "J Westling & CO., LLC", location: "Elkhorn, NE", amount: 1000 },
      { name: "Legacy Family Farms LLC", location: "West Point, NE", amount: 750 },
      { name: "Great Plains Communications, INC.", location: "Blair, NE", amount: 577 },
      { name: "Cp Strategies, LLC", location: "Lincoln, NE", amount: 327 },
      { name: "Consolidated Companies, INC.", location: "Lincoln, NE", amount: 277 },
    ],
    individual: [
      { name: "Arthur Dantchik", location: "Bala Cynwyd, PA", amount: 6000 },
      { name: "Harry Knobbe", location: "West Point, NE", amount: 5000 },
      { name: "Timothy Odell", location: "Blair, NE", amount: 2200 },
      { name: "Joann Japp", location: "Blair, NE", amount: 2000 },
      { name: "John Japp", location: "Knoxville, TN", amount: 1500 },
      { name: "Diane Trofholz", location: "Blair, NE", amount: 1300 },
      { name: "David Harrig", location: "Gretna, NE", amount: 1000 },
      { name: "Shawn Melotz", location: "Omaha, NE", amount: 701 },
      { name: "Amy Harper", location: "Kennard, NE", amount: 500 },
      { name: "Marjorie Hoier", location: "Herman, NE", amount: 500 },
    ],
  },
  "Cally Ideus": {
    committeeName: "Ideus For Nebraska",
    totalRaised: 61922,
    asOf: "2023\u20132026 NADC filings (cycle to date)",
    individualDonorCount: 20,
    individualAverage: 562,
    geography: {
      individual: { nebraska: 7634, outOfState: 3603 },
      corporate: { nebraska: 8304, outOfState: 4750 },
    },
    corporate: [
      { name: "Pavelka Insurance Agency LLC", location: "Holdredge, NE", amount: 2000 },
      { name: "Altria Client Services, INC. (Va)", location: "Richmond, VA", amount: 2000 },
      { name: "Cino Security", location: "Middle Island, NY", amount: 1000 },
      { name: "Alliance Omaha Soccer LLC DBA Union Omaha", location: "Papillion, NE", amount: 1000 },
      { name: "Husch Blackwell LLP", location: "St Louis, MO", amount: 1000 },
      { name: "Union Pacific Railroad Company", location: "Omaha, NE", amount: 1000 },
      { name: "Kissel Kohout Es Associates LLC", location: "Lincoln, NE", amount: 575 },
      { name: "Radcliffe & Associates (Radcliffe Gilbertson & Brady)", location: "Lincoln, NE", amount: 575 },
      { name: "American Property Casualty Insurance Association", location: "Chicago, IL", amount: 500 },
      { name: "Catalyst Public Affairs (68508)", location: "Lincoln, NE", amount: 500 },
    ],
    individual: [
      { name: "Myron Dorn", location: "Adams, NE", amount: 1250 },
      { name: "Mike Embry", location: "Chesterfield, MI", amount: 1041 },
      { name: "Brad Christian", location: "Clatonia, NE", amount: 1041 },
      { name: "Mark Gaunya", location: "Hopkinton, MA", amount: 1000 },
      { name: "Janie Vrtiska", location: "Eagle, NE", amount: 812 },
      { name: "Roger Lempke", location: "Lincoln, NE", amount: 521 },
      { name: "Donavan Jones", location: "Raymore, MO", amount: 521 },
      { name: "Kristy Roth", location: "Roca, NE", amount: 500 },
      { name: "Terry Doyle", location: "Beatrice, NE", amount: 500 },
      { name: "Andrew Maschmann", location: "Beatrice, NE", amount: 500 },
    ],
  },
  "Janet M. Bock": {
    committeeName: "Janet Bock For Legislature",
    totalRaised: 51607,
    asOf: "2023\u20132026 NADC filings (cycle to date)",
    individualDonorCount: 5,
    individualAverage: 450,
    geography: {
      individual: { nebraska: 2000, outOfState: 250 },
      corporate: null,
    },
    corporate: [
    ],
    individual: [
      { name: "Matthew Johnson", location: "Omaha, NE", amount: 500 },
      { name: "Don Schuller", location: "Wymore, NE", amount: 500 },
      { name: "Steven Mitchell", location: "Burchard, NE", amount: 500 },
      { name: "Lori Ashmore", location: "Lincoln, NE", amount: 500 },
      { name: "Cheryl Goin", location: "Bloomfield Hills, MI", amount: 250 },
    ],
  },
  "Chris Anderson": {
    committeeName: "Anderson For Nebraska",
    totalRaised: 45394,
    asOf: "2023\u20132026 NADC filings (cycle to date)",
    individualDonorCount: 37,
    individualAverage: 512,
    geography: {
      individual: { nebraska: 10205, outOfState: 8736 },
      corporate: { nebraska: 1500, outOfState: 0 },
    },
    corporate: [
      { name: "Richland Homes LLC", location: "Omaha, NE", amount: 1500 },
    ],
    individual: [
      { name: "Zachary Helvey", location: "Manhattan Beach, CA", amount: 2500 },
      { name: "Bob Arritt", location: "Omaha, NE", amount: 2000 },
      { name: "Claire Muselman", location: "West Des Moines, IA", amount: 1041 },
      { name: "Berniece Grewcock", location: "Omaha, NE", amount: 1000 },
      { name: "Mike Faust", location: "Omaha, NE", amount: 1000 },
      { name: "Scott Nowlin", location: "Oviedo, FL", amount: 521 },
      { name: "Craig Allen", location: "San Antonio, TX", amount: 521 },
      { name: "Derek Gardner", location: "Fpo, AP", amount: 521 },
      { name: "Chandler Bigelow", location: "La Vista, NE", amount: 521 },
      { name: "Russell Teehan", location: "Colorado Springs, CO", amount: 521 },
    ],
  },
  "Cindy Chatt": {
    committeeName: "Chatt For Nebraska",
    totalRaised: 36067,
    asOf: "2023\u20132026 NADC filings (cycle to date)",
    individualDonorCount: 46,
    individualAverage: 424,
    geography: {
      individual: { nebraska: 19489, outOfState: 0 },
      corporate: { nebraska: 5800, outOfState: 2000 },
    },
    corporate: [
      { name: "Dianne S Lozier Trust", location: "Omaha, NE", amount: 2500 },
      { name: "Altria Client Services, INC. (Va)", location: "Richmond, VA", amount: 2000 },
      { name: "Jensen Rogert Associates, INC.", location: "Lincoln, NE", amount: 1000 },
      { name: "Consolidated Companies, INC.", location: "Lincoln, NE", amount: 750 },
      { name: "Radcliffe & Associates (Radcliffe Gilbertson & Brady)", location: "Lincoln, NE", amount: 250 },
      { name: "Lindsay Harr MacDonald", location: "Lincoln, NE", amount: 100 },
      { name: "Zulkoski Weber, LLC", location: "Lincoln, NE", amount: 100 },
      { name: "American Communications Group, INC.", location: "Lincoln, NE", amount: 100 },
      { name: "Mueller Robak, LLC", location: "Lincoln, NE", amount: 100 },
      { name: "Nebraska Rural Electric Association", location: "Lincoln, NE", amount: 100 },
    ],
    individual: [
      { name: "Roger Brodersen", location: "Omaha, NE", amount: 5000 },
      { name: "Kevin Brenneis", location: "Tekamah, NE", amount: 3726 },
      { name: "Randy Olson", location: "Tekamah, NE", amount: 1000 },
      { name: "Tom Shramek", location: "Tekamah, NE", amount: 1000 },
      { name: "Janis Connealy", location: "Tekamah, NE", amount: 500 },
      { name: "Sarah Chatt", location: "Tekamah, NE", amount: 500 },
      { name: "Justin Hanshew", location: "Oakland, NE", amount: 500 },
      { name: "Walter Lydick", location: "Tekamah, NE", amount: 500 },
      { name: "Diane Rogert", location: "Herman, NE", amount: 500 },
      { name: "Bret Brodersen", location: "Herman, NE", amount: 500 },
    ],
  },
  "Ben Blodgett": {
    committeeName: "Blodgett For 34",
    totalRaised: 33335,
    asOf: "2023\u20132026 NADC filings (cycle to date)",
    individualDonorCount: 4,
    individualAverage: 462,
    geography: {
      individual: { nebraska: 850, outOfState: 1000 },
      corporate: { nebraska: 8750, outOfState: 0 },
    },
    corporate: [
      { name: "I.B.E.W. Local Union No. 22 ( IBEW Local 22 )", location: "Omaha, NE", amount: 5000 },
      { name: "Nebraska & Southwest Iowa Building & Construction Trades Council", location: "Omaha, NE", amount: 2500 },
      { name: "Steamfitters & Plumbers  L.U. 464", location: "Omaha, NE", amount: 1000 },
      { name: "Nebraska State AFL-CIO", location: "Lincoln, NE", amount: 250 },
    ],
    individual: [
      { name: "Christopher Callihan", location: "Woodbridge, VA", amount: 1000 },
      { name: "Dawn Blodgett", location: "Central City, NE", amount: 500 },
      { name: "Judith Vohland", location: "Grand Island, NE", amount: 250 },
      { name: "Lisa Albers", location: "Grand Island, NE", amount: 100 },
    ],
  },
  "Janell Anderson Ehrke": {
    committeeName: "Anderson Ehrke For Legislature",
    totalRaised: 32681,
    asOf: "2023\u20132026 NADC filings (cycle to date)",
    individualDonorCount: 22,
    individualAverage: 978,
    geography: {
      individual: { nebraska: 21525, outOfState: 0 },
      corporate: { nebraska: 2600, outOfState: 0 },
    },
    corporate: [
      { name: "Consolidated Companies, INC.", location: "Lincoln, NE", amount: 750 },
      { name: "Kissel Kohout Es Associates LLC", location: "Lincoln, NE", amount: 350 },
      { name: "Kelley Plucker, LLC", location: "Omaha, NE", amount: 100 },
      { name: "Radcliffe & Associates (Radcliffe Gilbertson & Brady)", location: "Lincoln, NE", amount: 100 },
      { name: "Zulkoski Weber, LLC", location: "Lincoln, NE", amount: 100 },
      { name: "Lindsay Harr MacDonald", location: "Lincoln, NE", amount: 100 },
      { name: "Nebraska Retail Federation", location: "Lincoln, NE", amount: 100 },
      { name: "American Communications Group, INC.", location: "Lincoln, NE", amount: 100 },
      { name: "Nebraska Rural Electric Association", location: "Lincoln, NE", amount: 100 },
      { name: "Peetz & Schrader", location: "Lincoln, NE", amount: 100 },
    ],
    individual: [
      { name: "Jason Anderson", location: "Arapahoe, NE", amount: 10000 },
      { name: "Douglas Winz", location: "Holdrege, NE", amount: 2500 },
      { name: "Gary Robison", location: "Bertrand, NE", amount: 2000 },
      { name: "Bob Isaacson", location: "Holdrege, NE", amount: 1000 },
      { name: "Allen Fredrickson", location: "Omaha, NE", amount: 1000 },
      { name: "Dakotah Hueftle", location: "Holdrege, NE", amount: 1000 },
      { name: "Nancy Knutson", location: "Wilsonville, NE", amount: 500 },
      { name: "Duane Murdoch", location: "Oxford, NE", amount: 500 },
      { name: "Jeff Krejdl", location: "Oxford, NE", amount: 500 },
      { name: "Vicki Westcott", location: "Holdrege, NE", amount: 500 },
    ],
  },
  "Dawson Brunswick": {
    committeeName: "Brunswick For Legislature",
    totalRaised: 31229,
    asOf: "2023\u20132026 NADC filings (cycle to date)",
    individualDonorCount: 6,
    individualAverage: 850,
    geography: {
      individual: { nebraska: 5100, outOfState: 0 },
      corporate: { nebraska: 6969, outOfState: 1798 },
    },
    corporate: [
      { name: "Cox Communications", location: "Wichita, KS", amount: 1298 },
      { name: "Great Plains Communications, INC.", location: "Blair, NE", amount: 1048 },
      { name: "Union Pacific Railroad Company", location: "Omaha, NE", amount: 1000 },
      { name: "Arl Credit Services, INC DBA Columbus Credit Services", location: "Columbus, NE", amount: 1000 },
      { name: "Kissel Kohout Es Associates LLC", location: "Lincoln, NE", amount: 548 },
      { name: "Driver Chiropratic LLC", location: "Columbus, NE", amount: 500 },
      { name: "Hb Strategies", location: "Jefferson City, MO", amount: 500 },
      { name: "Cp Strategies, LLC", location: "Lincoln, NE", amount: 298 },
      { name: "Radcliffe & Associates (Radcliffe Gilbertson & Brady)", location: "Lincoln, NE", amount: 298 },
      { name: "Nebraska Strategies", location: "Lincoln, NE", amount: 298 },
    ],
    individual: [
      { name: "Chad Van Cleave", location: "Columbus, NE", amount: 2500 },
      { name: "Jill Ramaekers", location: "Columbus, NE", amount: 1000 },
      { name: "Travis Tessendorf", location: "Columbus, NE", amount: 1000 },
      { name: "Dennis Grennan", location: "Columbus, NE", amount: 300 },
      { name: "Paul Strommen", location: "Sidney, NE", amount: 250 },
      { name: "Lukas Wenz", location: "Lincoln, NE", amount: 50 },
    ],
  },
  "Joe Johnson": {
    committeeName: "Johnson For Legislature",
    totalRaised: 18608,
    asOf: "2023\u20132026 NADC filings (cycle to date)",
    individualDonorCount: 11,
    individualAverage: 245,
    geography: {
      individual: { nebraska: 2690, outOfState: 0 },
      corporate: { nebraska: 3692, outOfState: 0 },
    },
    corporate: [
      { name: "Midwest Land Development,LLC", location: "Lincoln, NE", amount: 1000 },
      { name: "Mueller Robak, LLC", location: "Lincoln, NE", amount: 592 },
      { name: "Kissel Kohout Es Associates LLC", location: "Lincoln, NE", amount: 500 },
      { name: "Radcliffe & Associates (Radcliffe Gilbertson & Brady)", location: "Lincoln, NE", amount: 342 },
      { name: "Baird Holm, LLP", location: "Omaha, NE", amount: 200 },
      { name: "Consolidated Companies, INC.", location: "Lincoln, NE", amount: 200 },
      { name: "Nebraska Strategies", location: "Lincoln, NE", amount: 192 },
      { name: "Zulkoski Weber, LLC", location: "Lincoln, NE", amount: 192 },
      { name: "Lindsay Harr MacDonald", location: "Lincoln, NE", amount: 192 },
      { name: "J Park, LLC", location: "Nebraska City, NE", amount: 100 },
    ],
    individual: [
      { name: "Jon Watts", location: "Kearney, NE", amount: 1000 },
      { name: "Michael Morgan", location: "Kearney, NE", amount: 250 },
      { name: "Denise Lowry", location: "Cario, NE", amount: 250 },
      { name: "Paul Strommen", location: "Sidney, NE", amount: 250 },
      { name: "Nate McHargue", location: "Lincoln, NE", amount: 240 },
      { name: "Teresa Johnson", location: "South Sioux City, NE", amount: 200 },
      { name: "Heath Mello", location: "Omaha, NE", amount: 200 },
      { name: "Joe Murray", location: "Firth, NE", amount: 100 },
      { name: "L Lippincott", location: "Central City, NE", amount: 100 },
      { name: "James Friesen", location: "Kearney, NE", amount: 50 },
    ],
  },
  "Christy Knorr": {
    committeeName: "Neighbors For Christy Knorr",
    totalRaised: 14324,
    asOf: "2023\u20132026 NADC filings (cycle to date)",
    individualDonorCount: 19,
    individualAverage: 202,
    geography: {
      individual: { nebraska: 2345, outOfState: 1500 },
      corporate: null,
    },
    corporate: [
    ],
    individual: [
      { name: "Megan Hull", location: "Oakland, CA", amount: 1000 },
      { name: "Scott Winkler", location: "Lavista, NE", amount: 500 },
      { name: "Denise Powell", location: "Omaha, NE", amount: 500 },
      { name: "Scott Winkler", location: "La Vista, NE", amount: 500 },
      { name: "Christina Price", location: "Granite Falls, NC", amount: 250 },
      { name: "Allison Thompson", location: "Omaha, NE", amount: 250 },
      { name: "Zoe Miller", location: "Omaha, NE", amount: 250 },
      { name: "Nicole Ramey", location: "Warner Robins, GA", amount: 175 },
      { name: "Kayla Nelson", location: "Omaha, NE", amount: 100 },
      { name: "Ursula Flournoy", location: "Warner Robins, GA", amount: 50 },
    ],
  },
  "Jeremy Heneger": {
    committeeName: "Committee To Elect Jeremy Heneger For Legislature",
    totalRaised: 12765,
    asOf: "2023\u20132026 NADC filings (cycle to date)",
    individualDonorCount: 4,
    individualAverage: 750,
    geography: {
      individual: { nebraska: 600, outOfState: 2400 },
      corporate: { nebraska: 500, outOfState: 0 },
    },
    corporate: [
    ],
    individual: [
      { name: "Rebecca Wolzenski", location: "Wildwood, MO", amount: 1000 },
      { name: "Scott Shenker", location: "Berkeley, CA", amount: 1000 },
      { name: "Trudy Clark", location: "Lincoln, NE", amount: 600 },
      { name: "Monty Eich", location: "San Jose, CA", amount: 400 },
    ],
  },
};

// Merged lookup, keyed by candidate name -- this is what elections2026.js
// actually reads from. Candidate names are unique across these races, so a
// flat merge is safe.
const candidateDonors = {
  ...governorDonors,
  ...secretaryOfStateDonors,
  ...attorneyGeneralDonors,
  ...treasurerDonors,
  ...auditorDonors,
  ...legislatureDonors,
};

module.exports = {
  governorDonors,
  secretaryOfStateDonors,
  attorneyGeneralDonors,
  treasurerDonors,
  auditorDonors,
  legislatureDonors,
  candidateDonors,
};
