// Sample data shaped exactly like the normalized output of src/legiscan.js.
// Used automatically when no LEGISCAN_API_KEY is configured, so the site
// is fully browsable before you add a real key.

const mockBills = [
  {
    id: "mock-1",
    number: "LB246",
    title: "Adopt the Nebraska Broadband Bridge Act",
    description:
      "Provides grants to expand high-speed internet access in unserved and underserved rural areas of the state.",
    status: "committee",
    statusLabel: "In Committee",
    committee: "Transportation and Telecommunications",
    sponsors: ["Sen. K. Bostelman"],
    introducedDate: "2026-01-08",
    lastActionDate: "2026-02-11",
    lastAction: "Referred to Transportation and Telecommunications Committee for hearing.",
    url: "https://nebraskalegislature.gov/bills/view_bill.php?DocumentID=1",
  },
  {
    id: "mock-2",
    number: "LB318",
    title: "Change provisions relating to property tax valuation appeals",
    description:
      "Revises the timeline and evidentiary standards county boards of equalization must follow when hearing property valuation protests.",
    status: "general_file",
    statusLabel: "General File",
    committee: "Revenue",
    sponsors: ["Sen. R. Linehan", "Sen. B. Dorn"],
    introducedDate: "2026-01-14",
    lastActionDate: "2026-02-20",
    lastAction: "Advanced to General File by Revenue Committee, 7-0.",
    url: "https://nebraskalegislature.gov/bills/view_bill.php?DocumentID=2",
  },
  {
    id: "mock-3",
    number: "LB102",
    title: "Change school district reorganization and funding provisions",
    description:
      "Adjusts state aid formulas for school districts undergoing consolidation and clarifies transportation funding.",
    status: "select_file",
    statusLabel: "Select File",
    committee: "Education",
    sponsors: ["Sen. L. Murman"],
    introducedDate: "2026-01-07",
    lastActionDate: "2026-03-02",
    lastAction: "Placed on Select File with committee amendments pending.",
    url: "https://nebraskalegislature.gov/bills/view_bill.php?DocumentID=3",
  },
  {
    id: "mock-4",
    number: "LB55",
    title: "Adopt the Nebraska Groundwater Sustainability Act",
    description:
      "Establishes new monitoring and reporting requirements for natural resources districts managing irrigation-heavy aquifers.",
    status: "final_reading",
    statusLabel: "Final Reading",
    committee: "Natural Resources",
    sponsors: ["Sen. T. Aschford", "Sen. E. Wayne"],
    introducedDate: "2026-01-06",
    lastActionDate: "2026-03-10",
    lastAction: "Passed Select File 41-3, placed on Final Reading.",
    url: "https://nebraskalegislature.gov/bills/view_bill.php?DocumentID=4",
  },
  {
    id: "mock-5",
    number: "LB19",
    title: "Change minimum wage provisions for tipped employees",
    description:
      "Adjusts the base cash wage employers may pay tipped workers before tip credit is applied.",
    status: "governor",
    statusLabel: "With Governor",
    committee: "Business and Labor",
    sponsors: ["Sen. J. Cavanaugh"],
    introducedDate: "2026-01-05",
    lastActionDate: "2026-03-18",
    lastAction: "Passed Final Reading 29-18, presented to Governor.",
    url: "https://nebraskalegislature.gov/bills/view_bill.php?DocumentID=5",
  },
  {
    id: "mock-6",
    number: "LB7",
    title: "Adopt the Volunteer Emergency Responder Recruitment Act",
    description:
      "Creates a tax credit for volunteer firefighters and rescue squad members who complete annual training hours.",
    status: "signed",
    statusLabel: "Signed into Law",
    committee: "Revenue",
    sponsors: ["Sen. M. Halloran", "Sen. R. Ballard"],
    introducedDate: "2026-01-05",
    lastActionDate: "2026-03-22",
    lastAction: "Approved by Governor.",
    url: "https://nebraskalegislature.gov/bills/view_bill.php?DocumentID=6",
  },
  {
    id: "mock-7",
    number: "LB412",
    title: "Change occupational licensing requirements for cosmetology",
    description:
      "Reduces required training hours and adds reciprocity for licenses held in other states.",
    status: "vetoed",
    statusLabel: "Vetoed",
    committee: "Business and Labor",
    sponsors: ["Sen. C. Hansen"],
    introducedDate: "2026-01-15",
    lastActionDate: "2026-03-25",
    lastAction: "Vetoed by Governor; veto override not attempted.",
    url: "https://nebraskalegislature.gov/bills/view_bill.php?DocumentID=7",
  },
  {
    id: "mock-8",
    number: "LB88",
    title: "Change provisions relating to concealed handgun permits",
    description:
      "Modifies training and renewal requirements for concealed carry permit holders.",
    status: "failed",
    statusLabel: "Indefinitely Postponed",
    committee: "Judiciary",
    sponsors: ["Sen. T. Brewer"],
    introducedDate: "2026-01-09",
    lastActionDate: "2026-02-27",
    lastAction: "Indefinitely postponed by Judiciary Committee, 4-4 tie.",
    url: "https://nebraskalegislature.gov/bills/view_bill.php?DocumentID=8",
  },
  {
    id: "mock-9",
    number: "LB501",
    title: "Provide for a statewide childcare workforce grant program",
    description:
      "Directs the Department of Health and Human Services to administer wage-support grants for licensed childcare workers.",
    status: "introduced",
    statusLabel: "Introduced",
    committee: "Health and Human Services",
    sponsors: ["Sen. J. Day", "Sen. A. Hunt"],
    introducedDate: "2026-01-22",
    lastActionDate: "2026-01-22",
    lastAction: "Introduced and referred to committee.",
    url: "https://nebraskalegislature.gov/bills/view_bill.php?DocumentID=9",
  },
  {
    id: "mock-10",
    number: "LB160",
    title: "Change the Nebraska Environmental Trust Act",
    description:
      "Expands eligible uses of Environmental Trust Fund grants to include municipal recycling infrastructure.",
    status: "committee",
    statusLabel: "In Committee",
    committee: "Natural Resources",
    sponsors: ["Sen. G. Blood"],
    introducedDate: "2026-01-12",
    lastActionDate: "2026-02-05",
    lastAction: "Hearing held; committee took no immediate action.",
    url: "https://nebraskalegislature.gov/bills/view_bill.php?DocumentID=10",
  },
];

module.exports = { mockBills };
